Jenkinsfile, pom.xml, src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/utils/ClientChainData.java, src/main/java/cn/nukkit/utils/LoginChainData.java
Validate the JWT chain data with Mojang's Public Key so that spoofed players are not able to join the server unless `xbox-auth` is set to `false`.
=> Implement authentication for Xbox

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/network/protocol/LoginPacket.java, src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
This stops the server from throwing errors when a player with version 1.1.x or below joins due to the major change in protocol. Also changed the detection for incompatible protocol versions.
=> Support versions lower than 1.2 without throwing errors

src/main/java/cn/nukkit/utils/ChunkException.java
Exceptions used for control flow (e.g. ChunkException) shouldn't fill in their stacktrace. The stacktrace will never be used, and it's relatively expensive to generate. 
there may be other exceptions that need changing
=> don't fill stacktrace for control flow exceptions

src/main/java/cn/nukkit/item/Item.java, src/main/java/cn/nukkit/level/format/anvil/Chunk.java
In my Block restructuring PR I forgot to replace all uses of Reflection with the Block.get method.
=> Use Block.get instead of reflection fixes #74

src/main/java/cn/nukkit/level/Level.java
When a lava block (e.g. in a cave) is randomly ticked, it can spawn a fire block. The subsequent light updates from the temporary fire block cause adjacent chunks to load. Those chunks in turn (if they contain lava) may spawn more fire blocks etc. 
Fortunately there isn't anywhere near enough lava in a normal world for this to cause any runaway, but it does cause lots of unnecessary chunk loading / saving / unloading. 
There are two options
`1`: Don't have lighting updates load chunks (results in bad block lighting)
`2`: Don't randomly tick the edge chunks 
This PR implements option 2.  
It could be useful to also do `1` since lighting is handled client side anyway. Let me know?
=> random ticks shouldn't load chunks

src/main/java/cn/nukkit/block/BlockBed.java
Since direct was false in setBlock(), the blockEntities was sent prior to the blocks, which presumable made the client discard them and hence lose color information.
Fixes https://github.com/NukkitX/Nukkit/issues/93.
Also changed to BlockEntity.createBlockEntity at advice of Empire92 on Discord. This has no effect on the bug but looks saner than the dangling instantiation.
=> Fix bug where placing beds got a random color (#93).

src/main/java/cn/nukkit/entity/EntityLiving.java
Always set players in creative mode as breathing. 
This fixes https://github.com/NukkitX/Nukkit/issues/31.
=> Fix bubbles showing under water in creative (#31).

src/main/java/cn/nukkit/level/Level.java
- Fixes some block update issues due to the Level block update cache storing the index as a Short, which can't address any block above y=127. 
- Fixes an empty block update packet being sent for every block change. (essentially setting the 0,0,0 block to air). 
- Minor optimizations for sending block updates
=> Fix block updates above y=127

src/main/java/cn/nukkit/Nukkit.java, src/main/java/cn/nukkit/utils/MainLogger.java
There's a race condition in the logger class. If the server quits very quickly after startup on an error condition (typically an issue that can happen on incorrect configuration) the logger thread might not have time to print any buffered logs, and no output is written, which severely limits the possibilities to figure out the errors of said configuration. :-(
This patch addresses this issue by moving initialization code to the main thread instead of the logger thread to ensure that the worker thread can start working immediately, breaking out the waiting part of flushBuffer() so it's not done after the shutdown signal is received, and introducing a back-signalling mechanism from the worker thread to confirm to the main thread shutdown() method that it is indeed done.
=> Fix race condition in MainLogger.

src/main/java/cn/nukkit/block/Block.java, src/main/java/cn/nukkit/block/BlockLeaves.java, src/main/java/cn/nukkit/level/Explosion.java, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/utils/Hash.java
Reduce Position object creation by using primitive x,y,z for coordinates
Reduce BlockVector3 creation by using long as block hash
Oh gosh, it's still using a string for a block coordinate in BlockLeaves; kill me now.
=> Optimize block updates 1/3

src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/level/format/anvil/Chunk.java, src/main/java/cn/nukkit/level/format/anvil/palette/BiomePalette.java, src/main/java/cn/nukkit/level/format/anvil/palette/BlockDataPalette.java, src/main/java/cn/nukkit/level/generator/task/GenerationTask.java, src/main/java/cn/nukkit/level/generator/task/PopulationTask.java
By being able to directly modify the chunk, it avoids multiple expensive chunk.clone() calls during generation/population. 
This also fixes:
- Chunk population sometimes setting a chunk multiple times
- A ground cover issue with custom generators: https://i.imgur.com/ppKZjLK.gifv @DaPorkchop_
=> Direct async chunk modification with generator/populator

src/main/java/cn/nukkit/Player.java, src/main/java/co/aikar/timings/Timings.java
The timings system does a bunch of string concatenation / creating new timing objects even when it is disabled. It shouldn't do that.
=> optimize timings when not running

src/main/java/cn/nukkit/Server.java
A typical stumble-block for initial deployment of a git cloned version of Nukkit is forgetting the translation submodule. 
Yes, I know it is in the README. It's still easy to forgot; I've done it twice on different machines and ran into it a third time helping another developer set up Nukkit development.
This is a trivial change that will output a more suitable error message in case this has happened. The likelihood that the language files has disappeared in all other cases is rather slim.
=> Improved error message in case language files are missing.

src/main/java/cn/nukkit/command/Command.java, src/main/java/cn/nukkit/plugin/PluginManager.java
When `Command#permission` was null, the method ran a permission check for a null node, which caused an NPE.
Converts usages of `Map<Permissible, Permissible` to `Set<Permissible>`.
A WeakHashMap is still used via `Collections#newSetFromMap`.
=> Some permissions fixes & improvements

src/main/java/cn/nukkit/network/RakNetInterface.java
was described as having no issues when removed. however, i've found that it:
- causes issues with a number of server lists, causing it to show the version as `;0` and break other values
- breaks mcpe pinging software, for example [JRakNet's](https://github.com/JRakNet/JRakNet/blob/master/src/main/java/com/whirvis/jraknet/identifier/MinecraftIdentifier.java#L131-L132)
=> re-add version to motd string

pom.xml
The presence of this dependency on the classpath prevents plugins from using (libraries which depend on) slf4j.
This was first added in https://github.com/NukkitX/Nukkit/commit/822ff86d51ad8c723e02132b794cf44dc553267c - I assume because it was needed by "Oshi Core" - which has since been removed in https://github.com/NukkitX/Nukkit/commit/98d03a6f79a54ab4bed41d17a84cff0afbef837d
=> Don't shade no-op slf4j implementation

src/main/java/cn/nukkit/Server.java
Hi guys!
I'm trying to debug an issue in Nukkit, and the first thing I ran into was that it was difficult to debug. :-)
This patch facilitates debugging with breakpoints and single-stepping, by disabling the watchdog if debug.level is set to at least 2.
If there's another, established way of accomplishing this, please let me know.
=> Disable watchdog if debug.level is 2 or above, to enable breakpoints.

src/main/java/cn/nukkit/command/defaults/TimeCommand.java, src/main/java/cn/nukkit/level/Level.java
I added "noon", "sunset", "sunrise" and "midnight" arguments into "time" command's arguments.
=> supported time command arguments for "noon", "sunset", "sunrise", "midnight"

src/main/java/cn/nukkit/entity/Entity.java
In current minecraft, no damage is taken if any amount of water is beneath you, however unrealistic this is.
Fixes #118
=> Fix fall damage w/ water landing

src/main/java/cn/nukkit/block/BlockBricksStone.java
Fixes #233, BlockBrickStone has meta and should extend BlockSolidMeta.
=> BlockBrickStone extend BlockSolidMeta

src/main/java/cn/nukkit/block/Block.java, src/main/java/cn/nukkit/block/BlockID.java, src/main/java/cn/nukkit/block/BlockShulkerBox.java, src/main/java/cn/nukkit/block/BlockUndyedShulkerBox.java, src/main/java/cn/nukkit/level/Level.java, src/main/resources/recipes.json
This makes shulker boxes save content and name correctly so that when it is placed again, the contents are still there.
NOTE: In order for this to work in existing servers, the recipes.json file needs to be recreated, removing damage:16 from the recipe for the shulker box due to a weird bug where it becomes unusable end stone bricks
=> Fix shulker boxes not saving items

src/main/java/cn/nukkit/block/BlockCactus.java
Fixed bug that made creative players possible to freeze server with cactus blocks by just holding right mouse button with cactus on hand and placing it next to other cactus
=> Fix bug that can be used to slow down the server

.dockerignore, .gitignore, Dockerfile, README.md, docker-compose.yml
Add Docker configuration for building from source and running Nukkit using a `data` volume for persistent storage.
Verified building and running locally and with Minecraft 1.6 and various plugins. Image is ~128MB in size. 
Will build and run on arm64 (Raspberry Pi 3) using Docker [multi-arch support](https://blog.docker.com/2017/09/docker-official-images-now-multi-platform/). Use `arm64` tag on Dockerhub.
[Dockerhub repository and tags](https://hub.docker.com/r/ecliptik/nukkit/tags/).
Test with Dockerhub image,
```
#Make persistent data directory
mkdir -p ./data
#Run one-time to choose language and populate defaults
docker run -it --rm  -v `pwd`/data:/data ecliptik/nukkit
#Run with docker-compose to bring up data volume and listen on port 19132
docker-compose up
```
=> Add Docker configuration, update README with instructions.

src/main/java/cn/nukkit/Player.java
In commit `755d927`, knockback was changed and caused this to happen: https://streamable.com/j1kw3
This commit reverts that code and everything appears to be back to normal
=> Revert latest knockback changes

src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/blockentity/BlockEntity.java, src/main/java/cn/nukkit/blockentity/BlockEntityBeacon.java, src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java, src/main/java/cn/nukkit/blockentity/BlockEntityItemFrame.java, src/main/java/cn/nukkit/blockentity/BlockEntitySign.java, src/main/java/cn/nukkit/inventory/BaseInventory.java, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/level/format/anvil/Chunk.java, src/main/java/cn/nukkit/level/format/generic/BaseFullChunk.java, src/main/java/cn/nukkit/level/format/leveldb/Chunk.java
Containers were not marked for saving after being modified. This fix checks if the inventory holder is instanceof `BlockEntity` and marks it as dirty
=> Fix Container Saving

api/src/main/java/com/nukkitx/api/item/TierTypes.java, server/src/main/java/com/nukkitx/server/block/behavior/BlockBehaviors.java, server/src/main/java/com/nukkitx/server/block/behavior/CoalOreBlockBehavior.java, server/src/main/java/com/nukkitx/server/block/behavior/DiamondOreBlockBehavior.java, server/src/main/java/com/nukkitx/server/block/behavior/EmeraldOreBlockBehavior.java, server/src/main/java/com/nukkitx/server/block/behavior/GoldOreBlockBehavior.java, server/src/main/java/com/nukkitx/server/block/behavior/IronOreBlockBehavior.java, server/src/main/java/com/nukkitx/server/block/behavior/LapisLazuliOreBlockBehavior.java, server/src/main/java/com/nukkitx/server/block/behavior/NetherQuartzOreBlockBehavior.java, server/src/main/java/com/nukkitx/server/block/behavior/RedstoneOreBlockBehavior.java
This pull requests adds the (hopefully) correct drops for all of the ores in the game.
I think behaviour classes for the following circumstances should be added:
* Blocks that drop a different item ([reference](https://github.com/voxelwind/voxelwind/blob/master/server/src/main/java/com/voxelwind/server/game/level/block/behaviors/DropOtherItemBlockBehavior.java))
* Possibly for blocks that drop themselves (unless theres already a way that can be implemented)
---
I'm not quite sure if this will work since i obviously cant test it in game, but it compiles at least.
=> Rewrite: Add block behaviours for ores

src/main/java/cn/nukkit/level/Level.java
For example no xp from redstone ore if it's mined with stone pickaxe
=> Fix blocks dropping xp even mined with too low tier pickaxe

src/main/java/cn/nukkit/Player.java
Changed the maxDiff of the Level#canInteract method to 0.6 as 0.5 leaded to a glitch where blocks sometimes just disappear if players are "fast bridging" even though they have a good ping.
=> Fixed blocks disappear if you're "fast bridging"

src/main/java/cn/nukkit/Server.java
This ensures that the playerdata save task will be executed, even in the event of a server shutdown. When the server is stopped (e.g. through the `/stop` command, or otherwise) players are kicked and the server stopped in the same tick. Since the playerdata save action is queued as a task, it'll never be run since the task won't execute until the next tick (which never happens, since the server's stopping).
=> fix playerdata saving on server shutdown

src/main/java/cn/nukkit/Server.java
Now, you can easily put Server.getOnlinePlayers() (List of Players) and other lists with different types of CommandSender as second parameter of Server.broadcastMessage().
=> Usability of Server.broadcastMessage() improved.

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/entity/Entity.java, src/main/java/cn/nukkit/level/Level.java
Movement should never be sent using `level.addChunkPacket` as it gives no guarantee the recipient is actually viewing the entity moving.
=> Movement Fix

src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
Registering these is needed so plugins like Mob Plugin can spawn them without crashing the server
=> Register Pillager and Wandering Trader IDs to AddEntityPacket

src/main/java/cn/nukkit/network/Network.java
This pull request fixes a vulnerability where a compressed BatchPacket could contain thousands of packets and slow down the server. 
This is already fixed in the Pocketmine repo, as seen in this commit: https://github.com/pmmp/PocketMine-MP/commit/76c234e4e67cf6e9cadad2e1f7093a2f6e9e9ae5
=> Fix Dos Vulnerability

src/main/java/cn/nukkit/entity/item/EntityPotion.java
There is no special particle for instant splash potions in vanilla
Fixes #641
=> Change instant splash potion particles to normal

src/main/java/cn/nukkit/item/ItemPainting.java
The painting will display correctly when placed by an item after this fix.
=> Fix: Painting getting placed in different directions and inside the block

src/main/java/cn/nukkit/entity/Entity.java
Since `setNameTagAlwaysVisible()` edits **property** instead of **flag**, the `isNameTagAlwaysVisible()` also should check for **property**, not **flag**
=> Fix isNameTagAlwaysVisible() giving wrong result

src/main/java/cn/nukkit/Server.java
Kick the players before unregistering the plugins, so that the PlayerQuitEvent (and maybe other custom events) get called before the plugin is disabled, allowing for correct playerdata saving on a server shutdown
=> Switching the order of player kicking and plugin disabling on shutdown

src/main/java/cn/nukkit/network/protocol/ShowCreditsPacket.java
When the End Poem ends, the `ShowCreditsPacket` will be sent by the client to the server.
=> ShowCreditsPacket decode

src/main/java/cn/nukkit/Player.java
This fixes the bug where player can stand on dropped items or xp orbs but doesn't pick them up unless he is moving. This also make picking up big xp amounts much more nicer when you don't have to move for long time before you have picked up them all.
=> Check near entities even player doesn't move

src/main/java/cn/nukkit/block/BlockFire.java, src/main/java/cn/nukkit/block/BlockIce.java, src/main/java/cn/nukkit/block/BlockOreRedstoneGlowing.java, src/main/java/cn/nukkit/block/BlockSnowLayer.java, src/main/java/cn/nukkit/event/block/BlockFadeEvent.java
Called when a block fades, melts or disappears based on world conditions
Examples:
- Snow melting due to being near a light source.
- Ice melting due to being near a light source.
- Fire burning out after time, without destroying fuel block.
If a Block Fade event is cancelled, the block will not fade, melt or disappear.
=> BlockFadeEvent

src/main/java/cn/nukkit/utils/VarInt.java, src/test/java/cn/nukkit/test/VarIntTest.java
fixed the direct cast after the bit futzing and changed to a masked cast. 0x7FFFFFFF as a signed int was producing a 10-byte varint otherwise
=> fix signed varints

src/main/java/cn/nukkit/entity/item/EntityItem.java, src/main/java/cn/nukkit/item/ItemBookEnchanted.java, src/main/java/cn/nukkit/network/protocol/EntityEventPacket.java
I think this will be a useful feature for Nukkit as it will reduce entity count, which would be useful for users with poor hardware. I've tested it on play,skyblockpe.com without any issues for the past few days 
Additionally, Enchanted books shouldn’t be stackable. 👍
=> Item stack will autostack once dropped

src/main/java/cn/nukkit/entity/item/EntityItem.java
This decreases the cpu load caused by getNearbyEntities
=> Do not stack items on every tick

src/main/java/cn/nukkit/item/Item.java, src/main/java/cn/nukkit/item/enchantment/Enchantment.java
Bug：when use Item:getEnchantment, the Enchantment whose level is higher than its MaxLevel will be set to the MaxLevel
It makes trouble when developers want to customize item's enchantments
=> Fix enchantment bugs

src/main/java/cn/nukkit/Nukkit.java
There is new stuff and events added to Nukkit since API 1.0.8 so bumping the API version could be good idea so plugin developers can target their plugins to the new API if needed
=> Bump API version

src/main/java/cn/nukkit/Achievement.java, src/main/java/cn/nukkit/Server.java
Some coloured messages (`chat.type.achievement` and `nukkit.server.start`) had a problem with some languages because of differences in word order, which was not easy to notice in English as they look like nothing is wrong with them. This PR addresses the issue by `TextFormat.RESET`ing at the end of the message.
=> Fix some coloured messages

src/main/java/cn/nukkit/Player.java
- Remove item duplication on item pickup (Only if item exists in hotbar)
- Set hotbar slot to the item if it already exists instead of picking it up
=> Update block pickup to behave vanilla-like

src/main/java/cn/nukkit/blockentity/BlockEntityFurnace.java
This PR adds missing getters and setters for the burn time, burn duration, cook time and max time in BlockEntityFurnace.
=> Add missing getters/setters for BlockEntityFurnace

src/main/java/cn/nukkit/entity/data/Skin.java, src/main/java/cn/nukkit/level/particle/FloatingTextParticle.java
If a unique skin ID is not set, the client will display incorrect skins for everyone on the server.
=> Generate a skin ID if one does not exist.

src/main/java/cn/nukkit/nbt/tag/ListTag.java
The issue is the ListTag's entries should not have names.
https://minecraft.gamepedia.com/NBT_format#TAG_definition
> TAG_List: A list of tag payloads, without repeated tag IDs or any tag names.
So when the client receives an item which contains a list tag with named tags, the client remove them, so when the client attempts to interact with the item the server will reject the packets because the NBT tags mismatches.
To reproduce, I created this sample plugin which captures skeletons into bone items (the Entity.saveNBT() method adds ListTag with named values in "Pos", "Motion", and "Rotation", so I used that to fuel the example plugin)
The example plugin: https://gist.github.com/joserobjr/702a87fba0f9ffc8166f215065d51f2b
Steps to reproduce:
1. Install the example plugin
2. Start and login …
=> Fixes inventory issues with items with lists in the named tags.

src/main/java/cn/nukkit/Player.java
The PlayerToggleFlightEvent.isFlying were always being set to true when the player were able to fly, even when not flying. Now it will be set to true only when the player is actually starting to fly and false otherwise
=> Fix: Toggling flight in creative mode does not update the server correctly

src/main/java/cn/nukkit/block/BlockCauldron.java
Steps to reproduce:
1. Place a cauldron
2. Put water in it with a single bucket of water
3. Get a full stack of empty buckets (16)
4. Go in survival mode
5. Right click the cauldron with the stack. You will get 16 water buckets stacked.
This fixes it
=> Fixes water duplication bug with cauldron

src/main/java/cn/nukkit/Server.java
This was already fixed earlier but came back after some changes
=> Hide player data not found message if player data saving is disabled

src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/level/chunk/Chunk.java, src/main/java/cn/nukkit/level/chunk/ChunkBuilder.java, src/main/java/cn/nukkit/level/chunk/IChunk.java, src/main/java/cn/nukkit/level/chunk/LockableChunk.java, src/main/java/cn/nukkit/level/chunk/UnsafeChunk.java, src/main/java/cn/nukkit/level/generator/function/ChunkPopulateFunction.java, src/main/java/cn/nukkit/level/manager/LevelChunkManager.java, src/main/java/cn/nukkit/registry/RegistryProvider.java
Result of a long internal discussion about the best way to handle the issues caused by not all chunks being saved any more.
Prevents users from getting access to chunks that haven't been populated themselves, or had their neighbor chunks populated.
This is still not entirely safe, but it's a lot better than before, the remaining edge cases will be worked out in #1073 .
=> Prevent access to chunks that haven't had themselves or their neighbors populated

Dockerfile
* Workaround for missing man directories
* Fix for wrong permissions on /data, /app
* Faster builds (COPY ./ is generally bad)
NB: COPY ./ removes most benefits from caching - since it includes the Dockerfile,
even cosmetic changes to the Dockerfile result in a lengthy rebuild.
=> Update Dockerfile for bugfixes, efficiency improvements

src/main/java/cn/nukkit/entity/impl/misc/EntityAreaEffectCloud.java
This avoids the area effect clouds from detecting itself or anything not alive and shrinking faster than it should.
Reference: GameModsBr#132
=> [2.0] Fixes AreaEffectCloud collision rules

src/main/java/cn/nukkit/level/provider/leveldb/serializer/BlockEntitySerializer.java
=> [2.0] Fixes block entities not being saved before LevelDB serialization

src/main/java/cn/nukkit/block/BlockBarrier.java, src/main/java/cn/nukkit/registry/BlockRegistry.java
So the barrier properties are respected.
For example, a TNT could blow and drop it without this change.
Reference: GameModsBr#135
=> [2.0] Adds Barrier block

src/main/java/cn/nukkit/block/BlockButtonStone.java
Steps to reproduce the bug:
1. `/give <your-nick> stone_button`
2. Place the button somewhere
3. Break the button in survival mode with your hands
4. Notice that the button breaks quicker than it should and drops as an item while it should be destroyed
Reference: GameModsBr#166
=> [2.0] Fix stone_button break time and dropping without pickaxe

src/main/java/cn/nukkit/block/BlockButton.java
Steps to reproduce the bug:
1. `/give <your-nick> wooden_button` (or get in creative mode)
2. Place the button somewhere
3. Break the button in survival mode
4. Notice that the button won't stack with the other `63` buttons of the same type.
Reference: GameModsBr#165
=> [2.0] Fix the dropped button's damage value when a button is broken

src/main/java/cn/nukkit/entity/EntityLiving.java
noDamageTicks should make the entity completely invulnerable while active.
=> Fixed noDamageTicks not preventing damage when damage is less than previous damage

src/main/java/cn/nukkit/IPlayer.java
Updates IPlayer javadoc to inform reader what to expect as the return value
Reduces confusion when comparing with Bukkit API which returns Unix time millisecond
=> Update IPlayer javadoc to contain info about return value

src/main/java/cn/nukkit/level/Level.java
Spamming the time for the client every second is unnecessary and just causes more network load
=> Do not send time every second

src/main/java/cn/nukkit/entity/impl/misc/EntityTnt.java, src/main/java/cn/nukkit/entity/impl/vehicle/EntityTntMinecart.java
Primed TNTs were white all the time and wasn't growing in the last second before exploding.
Primed TNT minecarts were not working correctly and they were exploding kinda randomly on player interactions.
History and reference: GameModsBr#169
=> [2.0] Fixes primed TNT and TNT minecarts not blinking and growing when lit

src/main/java/cn/nukkit/level/provider/anvil/AnvilDataSerializer.java, src/main/java/cn/nukkit/level/provider/leveldb/serializer/LevelDBDataSerializer.java
NukkitX#1092 changed the generator settings to raw string but didn't update the serializers. This PR is merely to allow the `2.0` branch to build without errors again. It has not been tested in game yet.
=> [2.0] Fix build errors

src/main/java/cn/nukkit/level/LevelData.java, src/main/java/cn/nukkit/nbt/tag/StringTag.java
Related to #1171, #1092 and NukkitX/Languages#32
Fixes:
```java
Caused by: java.lang.IllegalArgumentException: Empty string not allowed
at cn.nukkit.nbt.tag.StringTag.<init>(StringTag.java:18) ~[classes/:?]
at cn.nukkit.nbt.tag.CompoundTag.putString(CompoundTag.java:97) ~[classes/:?]
at cn.nukkit.level.provider.leveldb.serializer.LevelDBDataSerializer.saveData(LevelDBDataSerializer.java:68) ~[classes/:?]
```
when starting a clean server.
To actually start the server it's also needed to manually configure the worlds in `nukkit.yml` as in:
https://github.com/NukkitX/Languages/pull/32/files for now.
=> [2.0] Fix a startup error

src/main/java/cn/nukkit/block/BlockStrippedLog.java
The block missed a `place` override, so the data were 2 bits shifted to the left.
Reference: GameModsBr#190
=> [2.0] Fixes wrong Stripped Log Block damage

src/main/java/cn/nukkit/entity/impl/BaseEntity.java, src/main/java/cn/nukkit/entity/impl/misc/EntityDroppedItem.java, src/main/java/cn/nukkit/entity/impl/misc/EntityXpOrb.java, src/main/java/cn/nukkit/item/ItemBucket.java, src/main/java/cn/nukkit/level/Explosion.java, src/main/java/cn/nukkit/level/Level.java
This fixes:
History and Reference: GameModsBr#196
=> [2.0] Fix explosion behaviour with waterlogged blocks and some other bugs

src/main/java/cn/nukkit/item/ItemMap.java
Right now, **everytime** we call `ItemMap.sendImage(Player player)`, the `BufferedImage` is loaded from NBT data, which seems to produce quite some overhead when dealing with a lot of maps.
My commit optimizes this a bit by creating a field for the `BufferedImage` and loading it lazily.
=> Optimize map image loading

pom.xml, src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/level/provider/leveldb/LevelDBProvider.java, src/main/java/cn/nukkit/registry/RegistryProvider.java
This makes NukkitX use Mojang's [leveldb-mcpe](https://github.com/Mojang/leveldb-mcpe) by default using [my JNI bindings](https://github.com/2pocket2edition/leveldb-mcpe-jni), falling back to [normal Java leveldb](https://github.com/dain/leveldb) if native libraries are not compiled for the current system.
Native libraries are available for the following platforms:
- Linux amd64
- Linux aarch64
- Linux armhf (Raspbian)
- Windows amd64
I added my Maven repo to `pom.xml`, if that's an issue I'll see if I can figure out how to publish artifacts to a remote repository.
=> Native LevelDB

pom.xml, src/main/java/cn/nukkit/level/chunk/Chunk.java, src/main/java/cn/nukkit/level/chunk/IChunk.java, src/main/java/cn/nukkit/level/chunk/LockableChunk.java, src/main/java/cn/nukkit/level/chunk/UnsafeChunk.java, src/main/java/cn/nukkit/level/generator/PopChunkManager.java, src/main/java/cn/nukkit/level/generator/function/ChunkGenerateFunction.java, src/main/java/cn/nukkit/level/generator/function/ChunkPopulateFunction.java, src/main/java/cn/nukkit/level/manager/LevelChunkManager.java, src/main/java/cn/nukkit/level/provider/leveldb/LevelDBProvider.java
Obtain a read-only lock on chunks before encoding them (the writing part is done outside of the lock). This should prevent (among other things) air-only chunks from being saved.
Depends on #1207.
=> Lock chunks for saving

pom.xml, src/main/java/cn/nukkit/level/chunk/Chunk.java, src/main/java/cn/nukkit/level/chunk/IChunk.java, src/main/java/cn/nukkit/level/generator/PopChunkManager.java, src/main/java/cn/nukkit/level/generator/function/ChunkGenerateFunction.java, src/main/java/cn/nukkit/level/generator/function/ChunkPopulateFunction.java
Removed calls to `setDirty(false)` after generation and population, ensuring that chunks are always saved. This is no longer a significant performance concern with native leveldb, and will be critical to ensuring consistent population behavior for #1073 and related PRs. Additionally, ensures that chunks will always be locked in a predictable order before population, solving a potential deadlock.
=> Always save all chunks

pom.xml, src/main/java/cn/nukkit/utils/Identifier.java
This optimizes `Identifier#fromString` in a number of ways:
- Re-use `Matcher` instance rather than creating a new one each time
- Use normal `HashMap` instead of `ConcurrentHashMap` for faster operations
- Use a `ReadWriteLock` for controlling access to the internal map (ensures we can make the most of `HashMap`'s performance advantage by allowing multiple readers)
- Force all names to be lower-cased (avoids `String#toLowerCase`, users really shouldn't be using capitalized identifier names in the first place)
- Store identifiers under the `minecraft` namespace in the map both with and without their namespace (makes lookup faster when a string is given without a prefix)
- Make `fromString(String)` contain the main method implementation, and `from(String, String)` be a proxy to …
=> Speed up `Identifier` lookups

src/main/java/cn/nukkit/form/window/FormWindow.java
Always creating a new Gson instance on every Json request is very unperformant.
(see https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/Gson.java#L195)
=> Use static Gson instance in FormWindow

src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorLava.java
Cause it's chucking out errors and doesn't serve too much of a purpose, I've commented out the lava spread.
=> [2.0] Disable lava spread in PopulatorLava

src/main/java/cn/nukkit/block/BlockLava.java, src/main/java/cn/nukkit/block/BlockLavaStill.java, src/main/java/cn/nukkit/block/BlockLiquid.java, src/main/java/cn/nukkit/block/BlockWater.java, src/main/java/cn/nukkit/block/BlockWaterStill.java, src/main/java/cn/nukkit/registry/BlockRegistry.java
I was getting kinda random crashes while I was testing stuff under the ocean:
```java
java.lang.StackOverflowError: null
at cn.nukkit.level.manager.LevelChunkManager.getLoadedChunk(LevelChunkManager.java:104) ~[classes/:?]
at cn.nukkit.level.manager.LevelChunkManager.getLoadedChunk(LevelChunkManager.java:117) ~[classes/:?]
at cn.nukkit.level.manager.LevelChunkManager.getChunk(LevelChunkManager.java:134) ~[classes/:?]
at cn.nukkit.level.manager.LevelChunkManager.getChunk(LevelChunkManager.java:129) ~[classes/:?]
at cn.nukkit.level.Level.getChunk(Level.java:2227) ~[classes/:?]
at cn.nukkit.level.Level.getBlock(Level.java:1332) ~[classes/:?]
at cn.nukkit.level.Level.getBlock(Level.java:1315) ~[classes/:?]
at cn.nukkit.block.BlockLiquid.getLiquidBlock(BlockLiquid.java:446) ~[classes/:?]
at …
```
=> [2.0] Fix crash when waterlogged flowing water meets still water

src/main/java/cn/nukkit/command/CommandUtils.java, src/main/java/cn/nukkit/command/defaults/SetWorldSpawnCommand.java, src/main/java/cn/nukkit/command/defaults/TeleportCommand.java, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/level/Location.java, src/main/java/cn/nukkit/level/manager/LevelChunkManager.java, src/main/java/cn/nukkit/player/Player.java
*  Fixes the `getY()` and `getZ()` functions in `Location` (previously returned x value)
*  Fixes the `add()` function in the `Location` class
*  Fixes regex matching in the `CommandUtils` class (always has 2 groups based on pattern, but group(1) might be null)
* Updates `getSafeSpawn()`:
*  find the correct 2 vertical air spaces in the (x, z) position
*  remove redundant bitmasks, and incorrect bitmask of y value
=> [2.0] Location and Teleport fixes

src/main/java/cn/nukkit/entity/EntityHuman.java, src/main/java/cn/nukkit/level/Level.java
MovePlayerPacket instead of MoveEntityAbsolutePacket should be used when moving EntityHuman.
=> override addMoment in EntityHuman

src/main/java/cn/nukkit/blockentity/BlockEntityFlowerPot.java
Steps to reproduce:
1. Place a flower pot
2. Add any flower to it right clicking the side of a block which have a solid block above
=> Fixes ghost flower on the side of the pot after adding a flower to a pot

src/main/java/cn/nukkit/level/Level.java
Example:
```java
Level level = getLevel();
level.getBlockAt(0, 80, -4);
```
Produces:
```java
java.lang.IndexOutOfBoundsException: z coordinate (-5) must not be negative
at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
at cn.nukkit.level.chunk.UnsafeChunk.checkBounds(UnsafeChunk.java:99)
at cn.nukkit.level.chunk.UnsafeChunk.checkBounds(UnsafeChunk.java:94)
at cn.nukkit.level.chunk.UnsafeChunk.getBlock(UnsafeChunk.java:142)
at cn.nukkit.level.chunk.Chunk.getBlock(Chunk.java:141)
at cn.nukkit.level.Level.getBlockAt(Level.java:2133)
at <caller>
```
=> [2.0] Fix IndexOutOfBoundsException with negative coordinates

pom.xml, src/main/java/cn/nukkit/block/BlockBarrel.java, src/main/java/cn/nukkit/block/BlockBeacon.java, src/main/java/cn/nukkit/block/BlockBed.java, src/main/java/cn/nukkit/block/BlockChest.java, src/main/java/cn/nukkit/block/BlockFurnace.java, src/main/java/cn/nukkit/block/BlockFurnaceBurning.java, src/main/java/cn/nukkit/blockentity/impl/BeaconBlockEntity.java, src/main/java/cn/nukkit/blockentity/impl/BlastFurnaceBlockEntity.java, src/main/java/cn/nukkit/blockentity/impl/ChestBlockEntity.java, src/main/java/cn/nukkit/blockentity/impl/EnchantingTableBlockEntity.java, src/main/java/cn/nukkit/blockentity/impl/FurnaceBlockEntity.java, src/main/java/cn/nukkit/blockentity/impl/SmokerBlockEntity.java, src/main/java/cn/nukkit/inventory/BarrelInventory.java, src/main/java/cn/nukkit/inventory/ChestInventory.java, src/main/java/cn/nukkit/inventory/ContainerInventory.java, src/main/java/cn/nukkit/inventory/DoubleChestInventory.java, src/main/java/cn/nukkit/inventory/InventoryType.java, src/main/java/cn/nukkit/inventory/PlayerEnderChestInventory.java, src/main/java/cn/nukkit/level/ChunkManager.java, src/main/java/cn/nukkit/level/chunk/UnsafeChunk.java, src/main/java/cn/nukkit/level/provider/leveldb/serializer/BlockEntitySerializer.java, src/main/java/cn/nukkit/level/provider/leveldb/serializer/EntitySerializer.java, src/main/java/cn/nukkit/player/Player.java, src/main/java/cn/nukkit/registry/BlockEntityRegistry.java, src/main/java/cn/nukkit/registry/BlockRegistry.java, src/main/java/cn/nukkit/utils/Identifier.java
Fixes some problems created with BlockEntities from the Protocol Library update. 
- added `loadAdditionalData` to `BlockEntitySerializer` and `EntitySerializer` loaders
- fixed typo of `BlockEntitySerializer` loading `position` `z` value as `y` value
- the `yaw` and `pitch` were being read incorrectly from `MovePlayerPacket`, causing placement of entities that have directions to be incorrect
- chunk `setBlockData()` was checking if `data = 0` as if it was `BlockId == AIR`, when we shouldn't be setting any block data in a null section
- Add Convenience methods for `setBlockDataAt` which accepts `Vector3i` position
- Allows beds to be placed on slabs
- Chest Changes:
- Changed to match Vanilla NBT saving (paired x/z only saves with primary that has pairlead set to true)
- updated NBT saving …
=> [2.0] Entity fixes

src/main/java/cn/nukkit/permission/PermissionAttachment.java
This PR simply removes the unused parameter from `PermissionAttachment.unsetPermission()`. This is technically a breaking change as any plugin using this method will have to provide a second parameter, however this should be fine as the target branch is already breaking enough.
=> [2.0] Remove unused parameter

src/main/java/cn/nukkit/Player.java
With current max inAirTicks player gets kicked for flying while falling from world's max build height to void
=> Increase max inAirTicks

src/main/java/cn/nukkit/inventory/BarrelInventory.java, src/main/java/cn/nukkit/inventory/ChestInventory.java, src/main/java/cn/nukkit/inventory/ContainerInventory.java, src/main/java/cn/nukkit/inventory/DoubleChestInventory.java, src/main/java/cn/nukkit/inventory/PlayerEnderChestInventory.java, src/main/java/cn/nukkit/inventory/ShulkerBoxInventory.java
removes duplicated `BlockEventPacket` code for `BlockEntities` with `InventoryTypes` that "open"
=> [2.0] create static method for sending BlockEventPackets 

src/main/java/cn/nukkit/block/BlockLiquid.java, src/main/java/cn/nukkit/event/block/BlockFromToEvent.java
Changes `BlockLiquid` functionality to use the `to` block returned  by the `BlockFromToEvent`. Also changes the `BlockFromToEvent` to allow Plugins to update the `To` block.
=> [1.0] Update BlockFromToEvent

src/main/java/cn/nukkit/block/BlockFallable.java, src/main/java/cn/nukkit/event/block/BlockFallEvent.java
Thrown when a block physics check is called. (gravel, sand, dragon egg, concrete powder, snow layers and anvil)
If a Block Fall event is cancelled, the block will not fall.
=> BlockFallEvent

src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/potion/Effect.java, src/main/java/cn/nukkit/potion/Potion.java
Originally, there were 2 speed IDs with different values, one of them being actual speed, and the other being swiftness. I removed the swiftness one & also replaced the swiftness effect initialization with haste.
=> Remove duplicate speed effect ID

src/main/java/cn/nukkit/blockentity/impl/DaylightDetectorBlockEntity.java, src/main/java/cn/nukkit/registry/BlockEntityRegistry.java
Added the DaylightDetector Block entity and register it. Not sure if my compund tag values are correct as I referred to https://minecraft.gamepedia.com/Daylight_Detector#Block_data
=> [2.0] Add DaylightDetector block entity (#1337)

src/main/java/cn/nukkit/entity/projectile/EntityEnderPearl.java
Fixes #1356
mimics vanilla MC behavior where the pearl does nothing on collision with an ender portal
=> [1.0] Kill enderpearl on collision with Nether portal

src/main/java/cn/nukkit/Player.java
The server was not removing the levels from the player server-side, so next time XP was gained, the old level value was sent to the client. 
Fixes #1374
=> [1.0] Remove player levels on enchant

src/main/java/cn/nukkit/command/defaults/OpCommand.java
A Fix because when you type normally /op without any arguments it shows %commands.op.description, now it works flawless.
=> Update Op Command Usage.

src/main/java/cn/nukkit/level/GlobalBlockPalette.java, src/main/java/cn/nukkit/nbt/stream/NBTInputStream.java
Somehow there are some issues when loading resources from the compiled jar, and reading it into a `byte[]` first fixes it.
Also fixes reading unsigned shorts from NBT tags.
=> Fix NBT loading errors (hotfix)

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/block/BlockSugarcane.java, src/main/java/cn/nukkit/event/player/PlayerJumpEvent.java, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/network/protocol/MoveEntityAbsolutePacket.java
=> [Redstone] Updates from master branch

src/main/java/cn/nukkit/block/BlockDoublePlant.java, src/main/java/cn/nukkit/block/BlockTallGrass.java
Fixes a few bugs with grass and double tallgrass.
- Fixed grass drops (dropped wheat instead of seeds on double plants).
- Fixed double tallgrass dropping double trallgrass instead of two normal grass.
- Adjusted seed drop percentage (it's 12.5% instead of 10% according to the wiki).
- Fixed bug where placing grass on top of already placed grass would place what was in the inventory and thus decremented the amount there.
=> [2.0] Fix grass drops and placing on already placed grass

src/main/java/cn/nukkit/command/defaults/SetWorldSpawnCommand.java
it sets it as a Vector3i anyway, so using the int in the success message makes sense. Also, the translation message wants ints instead of double/float
=> fix world spawn command

src/main/java/cn/nukkit/Player.java
Whatever this method is required for (something with vehicle interaction on mobile I guess) it surely doesn't have to run on every tick. Because of the usage of `getEntityPlayerLookingAt` not running this on every tick will improve the server performance especially when there are many players online. I didn't find any side effects from this change.
=> Don't run checkInteractNearby on every tick

src/main/java/cn/nukkit/entity/passive/EntityChicken.java, src/main/java/cn/nukkit/entity/passive/EntityCow.java, src/main/java/cn/nukkit/entity/passive/EntityPig.java, src/main/java/cn/nukkit/entity/passive/EntityRabbit.java, src/main/java/cn/nukkit/entity/passive/EntitySheep.java
This adds to Nukkit that e.g. when it died on fire, that it drops instead of raw food cooked as it should (vanilla behaviour).
=> Enhance mob drops

src/main/java/cn/nukkit/Server.java
see #1464 
apparently the additional check for files that end in `.dat` was, in fact, critical
=> filter files to be used for legacy playerdata conversion correctly

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/event/inventory/CraftItemEvent.java, src/main/java/cn/nukkit/inventory/CraftingManager.java, src/main/java/cn/nukkit/inventory/CraftingRecipe.java, src/main/java/cn/nukkit/inventory/ShapedRecipe.java, src/main/java/cn/nukkit/inventory/ShapelessRecipe.java, src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java, src/main/java/cn/nukkit/inventory/transaction/InventoryTransaction.java, src/main/java/cn/nukkit/inventory/transaction/action/CraftingTransferMaterialAction.java
=> Quick craft implementation.

src/main/java/cn/nukkit/level/GlobalBlockPalette.java
This should allow chunks to load if invalid blocks are contained within it.
=> Show 'Update Game!' block instead of throwing an exception.

src/main/java/cn/nukkit/network/protocol/CreativeContentPacket.java, src/main/resources/recipes.json, src/main/resources/runtime_item_ids.json
the Creative Net ID needs to be non-zero unique, so just using the item ID did not work for blocks that share IDs using meta/states.
=> [1.16] CreativeContentPacket fix

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/network/CompressBatchedPacket.java, src/main/java/cn/nukkit/network/CompressBatchedTask.java, src/main/java/cn/nukkit/network/Network.java, src/main/java/cn/nukkit/network/RakNetInterface.java, src/main/java/cn/nukkit/network/protocol/DataPacket.java
This PR renames the `Network.deflate_raw` and `Network.inflate_raw` methods to `Network.deflateRaw` and `Network.inflateRaw` to match the java method naming standard.
=> Fixes the Network raw inflater and deflater names

src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/entity/mob/EntitySnowGolem.java
Although the actual [Snow Golem implementation](https://github.com/Nukkit-coders/MobPlugin/blob/0832b1b3e52b0f871f60df0bc98cd88005914e92/src/main/java/nukkitcoders/mobplugin/entities/monster/walking/SnowGolem.java) lives in MobPlugin this stub class definition is necessary to ensure that invocations of `Entity.createEntity("SnowGolem", ...)` by MobPlugin actually succeed.
=> Add support for Snow Golem mobs

README.md
I recall hearing a while back that Cloudburst doesn't accept donations now that it is owned by CubeCraft, and so it would just be confusing to still have this on the readme when the link takes you to an empty page
=> Remove the donation message in README

src/main/java/cn/nukkit/potion/Potion.java
I'm sure this is not the correct way to fix this issue, but while playing this afternoon, my son found a bug while using a "splash potion of slowness  slowness IV" the very last splash potion available in your creative mode inventory.  When you attempt to use this potion, the server displays the following error and stack trace: 
```
22:21:20 [ERROR] Could not tick level "world": cn.nukkit.utils.ServerException: Effect id: 42 not found, potions.length = 256
at cn.nukkit.potion.Potion.getPotion(Potion.java:116)
at cn.nukkit.entity.item.EntityPotion.splash(EntityPotion.java:92)
at cn.nukkit.entity.item.EntityPotion.onUpdate(EntityPotion.java:156)
at cn.nukkit.level.Level.doTick(Level.java:824)
at cn.nukkit.Server.checkTickUpdates(Server.java:1066)
at cn.nukkit.Server.tick(Server.java:1148) …
```
=> Add a potion with id = 42

src/main/java/cn/nukkit/network/protocol/AdventureSettingsPacket.java
"flags2" is an unsigned integer which means it must be positive, and Nukkit defaults it to -1 which is invalid, but still allowed by the client for some reason.
=> Default value for "flags2" should be a postive integer

src/main/java/cn/nukkit/network/protocol/CreativeContentPacket.java
In the CreativeContentPacket, the number of creative item entries needs to be an unsigned var int, rather than a regular var int
=> Number of entries needs to be unsigned

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/event/player/PlayerAsyncPreLoginEvent.java
The event already contains the UUID, name, address and port - the first three of which are ways of identifying a player - so it makes sense to provide the XUID there as well (plus, i need it and others might too)
=> Add XUID to PlayerAsyncPreLoginEvent

src/main/java/cn/nukkit/level/Level.java
Fixes this error:
```
2020-11-17 17:48:35.407 [main] INFO  - §bVixikCZ§f[/127.0.0.1:54536] logged in with entity id 1 at (world, 128.0, 68.0409, 128.0)
2020-11-17 17:48:35.997 [main] INFO  - §eVixikCZ joined the game
2020-11-17 17:48:44.372 [main] FATAL - Unhandled exception executing command "mw tp UHC-1" in mw: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
at cn.nukkit.level.format.generic.BaseChunk.getBlockId(BaseChunk.java:130)
at cn.nukkit.level.Level.getSafeSpawn(Level.java:2938)
at cn.nukkit.level.Level.getSafeSpawn(Level.java:2923)
at MultiWorld.MultiWorld.onCommand(MultiWorld.java:194)
at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)
at …
```
=> Fix level loading

src/main/java/cn/nukkit/Player.java
Add TimeSinceRest to Player.
It will be useful for Phantom natural spawning and get how long the player doesn't sleep.
=> Add TimeSinceRest

src/main/java/cn/nukkit/metrics/Metrics.java, src/main/java/cn/nukkit/metrics/NukkitMetrics.java
This PR implements metrics using https://bstats.org. It supersedes #1421. (Cloudburst version: https://github.com/CloudburstMC/Server/pull/110)
As the PaperMC project has done, a bStats directory in the plugins folder is created with a config.yml. This is in case bStats is ported to Nukkit and plugins start to include it, so that the configuration is all in one place.
The link to the bStats page: https://bstats.org/plugin/server-implementation/Nukkit/10277
=> Implement bStats metrics

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/network/Network.java, src/main/java/cn/nukkit/network/protocol/FilterTextPacket.java, src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
This allows the client to recognize that items can be renamed.
Re-opened as the feature/1.16.100 branch was deleted.
=> Allow anvil items to be renamed

src/main/java/cn/nukkit/network/protocol/AvailableCommandsPacket.java
Source: [CloudburstMC/Protocol](https://github.com/CloudburstMC/Protocol/blob/develop/bedrock/bedrock-v419/src/main/java/com/nukkitx/protocol/bedrock/v419/BedrockPacketHelper_v419.java)
=> Update command param types

src/main/java/cn/nukkit/network/protocol/CraftingDataPacket.java
Technical explanation: Bedrock behaves much better when each recipe in the CraftingDataPacket is assigned a network ID, even when using client-authoritative inventories.
Fixes #1798.
=> Fix crafting in 1.16.210

src/main/java/cn/nukkit/block/BlockLava.java
Chinese wiki is 10 ticks, but English wiki is 5 ticks
But I test in a single machine (vanilla?), I think magma flow speed is not so fast
So I used 10 tick
(Google Translate)
=> Fix the flow speed of lava in nether

src/main/java/cn/nukkit/item/ItemEndCrystal.java
* Allows for end crystals to be placed using any block face.
* Only allow placement if two blocks above the bedrock or obsidian block are air & no other entities intersect the area.
=> EndCrystal Improvements

src/main/java/cn/nukkit/entity/item/EntityItem.java, src/main/java/cn/nukkit/entity/item/EntityXPOrb.java
This pr disables unnecessary player collision checking from dropped items and xp orbs. Idk what is the reason for this code to even exist since nearby entities for item pickups are checked by player anyways. Making every dropped item/xp orb entity not to do unnecessary entity collision checks can improve the performance a lot especially when there are many of them.
Also made xp orbs to only check the viewers instead of checking distance to all players in the world.
=> Dropped item & xp orb performance improvement

src/main/java/cn/nukkit/blockentity/BlockEntityChest.java
unpair should not be called when unloading chunks, only when breaking a paired chest.
=> Fix: Paired chests bug #1738

src/main/java/cn/nukkit/entity/data/Skin.java
Persona skins with empty `PlayFabId` cannot be seen by other players.
=> Fix Persona skins

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/entity/item/EntityFishingHook.java, src/main/java/cn/nukkit/entity/item/EntityItem.java, src/main/java/cn/nukkit/event/player/PlayerFishEvent.java
Add `PlayerFishEvent` that is called when player catches a fish. This event allows you to modify the dropped item (loot), the amount of experience given and the motion of the dropped item as well as let you to get the fishing hook entity.
This pr does NOT change the way starting and stopping fishing is handled. You may still use `PlayerInteractEvent` if you want to deny the usage of a fishing rod.
Fix #1692
=> Add PlayerFishEvent

src/main/java/cn/nukkit/level/GlobalBlockPalette.java
Some bedrock legacy states can be mapped to same runtime id. Make sure our `runtimeIdToLegacy` map is not overwritten and correct `legacyId` can be resolved.
=> Don't overwrite runtime2Legacy states

src/main/java/cn/nukkit/entity/Entity.java
No need for damage calculation if the entity is a player & the gamerule `falldamage` is false.
=> Entity fall calculation improvement

src/main/java/cn/nukkit/Player.java
The registry is super backwards and already rewritten in CB
=> Unregistered commands are still sent in AvailableCommandsPacket

src/main/java/cn/nukkit/Server.java
Hacked client can crash the server when trying to send this packet because `player.getName()` is null.
=> Fix crash when client sends SetPlayerGameTypePacket early

src/main/java/cn/nukkit/block/Block.java
For example, breaking a grass block with a pickaxe that has efficiency V would return "0.033" as the time it would take to break that block.
Obviously this is wrong, even with the enchantment. With my new fix, break time calculation will ensure its the correct tool before applying an enchantment bonus.
=> Fix Block#getBreakTime calculation when the wrong tool is used with an efficiency enchantment.

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/entity/item/EntityItem.java, src/main/java/cn/nukkit/entity/projectile/EntityArrow.java, src/main/java/cn/nukkit/entity/projectile/EntityProjectile.java, src/main/java/cn/nukkit/entity/projectile/EntityThrownTrident.java, src/main/java/cn/nukkit/item/ItemTrident.java
Support channeling enchantment, pickup mode and do some cleanup
=> Improvements for trident

src/main/java/cn/nukkit/Player.java
Data is already sent once in entity.sendData called from super.setDataProperty even if given targets doesn't contain the current player
=> Fix player data properties being sent twice

pom.xml
Fix: https://nvd.nist.gov/vuln/detail/CVE-2021-44832
=> Update log4j to 2.17.1 to fix CVE-2021-44832

pom.xml
this will remove the warning
"WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance."
on java 9 and above
=> Enable Multi-Release in jar manifest

src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/math/Vector3.java
Operations that only play with vector x y z values don't have to use getBlock like getSide overridden in Block currently does
=> Improve redstone performance

src/main/java/cn/nukkit/Player.java
A illegal client can send AnimationPacket with illegal Action, like CRITICAL_HIT. 
If the illegal client send too many these packets(like 1000 pps?), viewers' client will drop fps or crash
\* sorry my english is bad
=> fix a broadcast exploit in AnimationPacket

src/main/java/cn/nukkit/inventory/transaction/action/DropItemAction.java
Prevents that you can eat e.g. a golden apple directly, if you drop the item, the PlayerDropItemEvent is cancelled and you press right click.
=> fix direct eat bug

src/main/java/cn/nukkit/network/protocol/ResourcePacksInfoPacket.java, src/main/java/cn/nukkit/resourcepacks/AbstractResourcePack.java, src/main/java/cn/nukkit/resourcepacks/ResourcePack.java, src/main/java/cn/nukkit/resourcepacks/ResourcePackManager.java, src/main/java/cn/nukkit/resourcepacks/ZippedResourcePack.java
This PR implements native resource pack encryption support.
It seems now people usually encrypt their resource pack using thrid party websites such as [encryptmypack](https://encryptmypack.com)
Previously, people should use external plugins to add support for resource pack encryption such as [my plugin](https://github.com/alvin0319/RCEncryption).
Now we can enable resource pack encryption by adding `filename.key` 
This has potential BC-breaking changes.
=> Implement native resource pack encryption support

README.md, docker-compose.yml
The README.md explains how to setup a docker container with docker and docker-compose.
But the current version tells us to run a docker container with `--rm`. This will remove the volume after creation. 
If we want to create a persistent docker volume at the first start of the docker container, we need to give it a proper name (like nukkit-data, see PR) and to not set `--rm`,
In the docker-compose file we then need to tell docker-compose that the volume already exists (`external:true`) and tell the name of the already existing volume.
This way docker-compose will re-use the already existing docker volume and not create a new one.
This PR also gives the container a name in docker-compose and applies a restart policy (restart unless stopped).
=> Properly set up a docker volume and use it in docker-compose

pom.xml
There are 1 security vulnerabilities found in com.google.guava:guava 21.0
- [CVE-2018-10237](https://www.oscs1024.com/hd/CVE-2018-10237)
Upgrade com.google.guava:guava from 21.0 to 30.0-jre for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade com.google.guava:guava to 30.0-jre

src/main/java/cn/nukkit/Player.java
Requiring isResponse causes issues with inventory events and an item duplication glitch
=> Ignore isResponse in removeWindow for now

src/main/java/cn/nukkit/command/defaults/VersionCommand.java
This change separates authors so that instead of "Authors: xxFLORIIxxAROX" it looks like "Authors: xxFLORII, xxAROX".
=> Separate plugin authors with ", " in the version command

src/main/java/cn/nukkit/command/defaults/StatusCommand.java, src/main/java/cn/nukkit/utils/TextFormat.java
Fix those being able to bypass TextFormat.clean
=> Support new color codes

src/main/java/cn/nukkit/item/Item.java
Add setUnbreakable() and changes to isUnbreakable()
Codes like this:
```java
ItemSwordStone sword = Item.get(ItemID.STONE_SWORD);
sword.setNamedTag(sword.getNamedTag().putByte("Unbreakable", 1));
return sword;
```
Can be shortened into this:
```java
return Item.get(ItemID.STONE_SWORD).setUnbreakable();
```
=> Item unbreakable changes

.gitattributes, Dockerfile, Dockerfile.arm64, README.md
- Changed gradlew line endings to fix Docker build, fixes #2157
- Use more up to date JDK Docker image
- Expose UDP port by default
- Don't ask for language on first Docker run
- No git submodules are used anymore
=> Docker fixes & improvements

docker-compose.yml
This change just removes the following warning on Docker Compose:
```sh-session
$ docker compose build
WARN[0000] /Users/common/minecraft-nukkit/Nukkit/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid
```
My Docker Compose version:
```sh-session
$ docker compose version
Docker Compose version v2.30.3-desktop.1
```
See also https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313
=> Fix obsolete `version` attribute in docker-compose.yml

src/main/java/cn/nukkit/item/Item.java
Ensure consistent iteration order of creative items by using LinkedHashMap.
by @glorydark
=> feat(item): replace HashMap with LinkedHashMap in CreativeItems
