CloudburstMC/Nukkit

- src/main/java/cn/nukkit/block/BlockRedstoneDiode.java
> Remove debug message

- src/main/java/cn/nukkit/level/Level.java
https://github.com/boy0001/FastAsyncWorldedit/issues/869
> Fix setChunk concurrentModification

- src/main/java/cn/nukkit/block/BlockLava.java
> Fixed lava igniting invulnerable or dead entities.

- src/main/java/cn/nukkit/Player.java
java.lang.NullPointerException
at cn.nukkit.Player$1.run(Player.java:559)
> stop server crashing (not sure if this is the right way to do this)

- src/main/java/cn/nukkit/scheduler/ServerScheduler.java
- src/main/java/cn/nukkit/utils/Utils.java
Minor change the scheduler to use a Map instead of a PriorityQueue, and just map the task to the tick it's scheduled for. 
It'll perform better, though not noticeably unless some plugin submits thousands of tasks.
> Scheduler tweak

- .github/ISSUE_TEMPLATE.md
- src/main/java/cn/nukkit/command/SimpleCommandMap.java
- src/main/java/cn/nukkit/command/defaults/DebugPasteCommand.java
- src/main/java/cn/nukkit/utils/HastebinUtility.java
Example debugpaste:
https://hastebin.com/ajituvurap.php
> Update issue template + add debug command

- src/main/java/cn/nukkit/math/Vector3.java
They should both use the same hashcode.
> Vector3 should use the same hashcode as BlockVector3

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/utils/Watchdog.java
to dump the threads when the server stops responding
> add thread watchdog

- src/main/java/cn/nukkit/Player.java
Sends the chunks sooner. idk why nextChunkOrderRun was set to 5.
> Faster player spawning

- src/main/java/cn/nukkit/nbt/tag/IntTag.java
- src/main/java/cn/nukkit/nbt/tag/LongTag.java
> Add missing space in IntTag/LongTag toString().

- .gitignore
creativeitems.json and recipes.json were missing.
> Update .gitignore with new generated json files.

- src/main/java/cn/nukkit/Player.java
Fixes https://github.com/NukkitX/Nukkit/issues/104.
> Fix not being able to attack mobs and animals (#104)

- src/main/java/cn/nukkit/level/format/anvil/Chunk.java
- src/main/java/cn/nukkit/level/format/generic/BaseFullChunk.java
i.e. When the world doesn't have any BiomeColors because it's a map from PC.
> Fixes #129

- src/main/java/cn/nukkit/item/ItemFlintSteel.java
i know this looks horrible, but it works much better than the current one. it can:
- detect portals without corners
- doesn't only work on the Z axis (previous one was limited to that)
[gif of it working better than the old one](https://i.imgur.com/VI9Hejs.gif)
> better portal detection algorithm

- pom.xml
- src/main/java/cn/nukkit/block/BlockLava.java
- src/main/java/cn/nukkit/block/BlockLiquid.java
- src/main/java/cn/nukkit/block/BlockWater.java
- src/main/java/cn/nukkit/level/Level.java
Literally just ported this commit over to java:
https://github.com/pmmp/PocketMine-MP/commit/d03fdd5f728021fac3c7d0cfa841a89e2b49ccaf
I had to add the full version of fastutil, the old version is still there and overriding the full version because of a couple of conflicts between the two
> Fix liquid flowing

- src/main/java/cn/nukkit/block/BlockStairsWood.java
Wooden stairs will drop without a pickaxe
> Wooden stairs fix

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/block/BlockNetherPortal.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/level/EnumLevel.java
- src/main/java/cn/nukkit/level/generator/Nether.java
I don't want to submit this hacked-together nether implementation, but some people asked me to so here I am.
> [Hack] The nether

- src/main/java/cn/nukkit/level/generator/Nether.java
- src/main/java/cn/nukkit/level/generator/object/ore/OreType.java
- src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorGlowStone.java
...yeah. next time i should probably test code before submitting it. why would i write a nether generator without looking at it?
> fix terrain gen because i broke it

- src/main/java/cn/nukkit/block/BlockDoor.java
I'm not sure is it Nukkit or mob plugin bug but this fixes it
> Fix mobs and animals walk through doors

- src/main/java/cn/nukkit/Player.java
Fixes bugged level changes.
Download the JAR here: https://ci.nukkitx.com/job/NukkitX/job/dimension/
> Fix level changes

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/level/ChunkLoader.java
- src/main/java/cn/nukkit/level/Level.java
Also a couple of other improvements whilst I was at it.
> ChunkSendQueue NPE Fix Closes #247

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockCauldron.java
- src/main/java/cn/nukkit/block/BlockShulkerBox.java
- src/main/java/cn/nukkit/blockentity/BlockEntity.java
- src/main/java/cn/nukkit/blockentity/BlockEntityShulkerBox.java
- src/main/java/cn/nukkit/inventory/InventoryType.java
- src/main/java/cn/nukkit/inventory/ShulkerBoxInventory.java
[https://streamable.com/89rsi](https://streamable.com/89rsi)
> Add Shulker Boxes

- src/main/java/cn/nukkit/entity/item/EntityItem.java
In aquatic update items float on water, added that for Nukkit
> Make items float on water

- src/main/java/cn/nukkit/level/format/ChunkSection.java
- src/main/java/cn/nukkit/level/format/anvil/ChunkSection.java
- src/main/java/cn/nukkit/level/format/anvil/palette/BlockDataPalette.java
- src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java
- src/main/java/cn/nukkit/level/format/anvil/util/NibbleArray.java
- src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
- src/main/java/cn/nukkit/level/format/generic/EmptyChunkSection.java
- src/main/java/cn/nukkit/utils/bugreport/BugReportGenerator.java
Revert the palette optimisations which don't seem to give much benefit over a byte array for block data and less CPU time.
Builds: https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/pr%252Frevert-palette-optimization/
> Revert palette optimization

- src/main/java/cn/nukkit/Player.java
This fixes https://github.com/NukkitX/Nukkit/issues/267
> Fix inventory and chunk loading after dieing in another world

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/EntityLiving.java
- src/main/java/cn/nukkit/entity/item/EntityPotion.java
- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/utils/Watchdog.java
This PR fixxes the following bugs;
> General issue fixxes

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/level/EnumLevel.java
This creates the nether world if it doesn't exist and allow-nether is set to true in server.properties
> Create nether world if it doesn't exist

- src/main/java/cn/nukkit/ItemPotionLingering.java
- src/main/java/cn/nukkit/item/Item.java
- src/main/java/cn/nukkit/item/ItemEgg.java
> Fix stack sizes

- src/main/java/cn/nukkit/block/BlockShulkerBox.java
> Fix shulker box breaking

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/blockentity/BlockEntityCauldron.java
- src/main/java/cn/nukkit/entity/data/Skin.java
- src/main/java/cn/nukkit/item/ItemMap.java
- src/main/java/cn/nukkit/network/protocol/ClientboundMapItemDataPacket.java
- src/main/java/cn/nukkit/utils/BlockColor.java
- src/main/java/cn/nukkit/utils/DummyBossBar.java
> Reduce awt use

- src/main/java/cn/nukkit/block/BlockTrapdoor.java
Should close #312 I'd like the OP of the issue to test this though, please compile this for yourself and test this.
> Trapdoors appear to work now

- src/main/java/cn/nukkit/block/BlockFenceGate.java
- src/main/java/cn/nukkit/block/BlockFenceGateAcacia.java
- src/main/java/cn/nukkit/block/BlockFenceGateBirch.java
- src/main/java/cn/nukkit/block/BlockFenceGateDarkOak.java
- src/main/java/cn/nukkit/block/BlockFenceGateJungle.java
- src/main/java/cn/nukkit/block/BlockFenceGateSpruce.java
- src/main/java/cn/nukkit/block/BlockFenceNetherBrick.java
Same issue as what was with rails.
> Fix gate drops

- src/main/java/cn/nukkit/item/Item.java
I saw that the potato wasn't added to the itemlist.
Now it's added.
This also fixes #321.
> Added potato to Itemlist. 

- src/main/java/cn/nukkit/block/BlockConcretePowder.java
> Concrete powder becomes concrete when placing near water.

- src/main/java/cn/nukkit/entity/projectile/EntityProjectile.java
- src/main/java/cn/nukkit/entity/projectile/EntityThrownTrident.java
Fix the trident being deleted when it hits an entity. There are probably better ways, this is just the fix I came up with in a couple secs. Feel free to close and do properly.
> Fix trident

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/item/enchantment/Enchantment.java
- src/main/java/cn/nukkit/item/enchantment/EnchantmentMending.java
This has been tested by me, feel free to test before merge though.
> Add Mending Support

- src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java
Stops hoppers taking inputs from furnaces and adding into the result slot.
> Fix hoppers interacting with furnaces

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/block/BlockBeacon.java
- src/main/java/cn/nukkit/blockentity/BlockEntityBeacon.java
- src/main/java/cn/nukkit/inventory/BeaconInventory.java
- src/main/java/cn/nukkit/inventory/InventoryType.java
- src/main/java/cn/nukkit/network/protocol/types/NetworkInventoryAction.java
> [Can be merged] Beacon support

- src/main/java/cn/nukkit/blockentity/BlockEntityBeacon.java
- src/main/java/cn/nukkit/network/protocol/types/NetworkInventoryAction.java
Fixes transparency support for beacons.
Removes a left over debug message from when I was fixing transactions.
> Post beacon changes

- src/main/java/cn/nukkit/level/Level.java
> Fixed infinity durability.

- src/main/java/cn/nukkit/block/BlockMagma.java
- src/main/java/cn/nukkit/entity/EntityLiving.java
Fixed magma block damage and added check for sneaking
> Fix magma blocks

- src/main/java/cn/nukkit/entity/mob/EntityMob.java
- src/main/java/cn/nukkit/entity/passive/EntityAnimal.java
> Implemented name tags

- src/main/java/cn/nukkit/block/BlockHugeMushroomBrown.java
- src/main/java/cn/nukkit/block/BlockHugeMushroomRed.java
This PR fixxes the following bugs:
> Fixxed Mushroom block Silk touch

- src/main/java/cn/nukkit/block/BlockItemFrame.java
- src/main/java/cn/nukkit/level/Level.java
Fixes the issue we have spoken about in game Supreme
> Item frame fix

- src/main/java/cn/nukkit/entity/Entity.java
> No void damage on creative

- src/main/java/cn/nukkit/entity/item/EntityPotion.java
Make them break on collide with entity
Tested
> Improvements for splash potions

- src/main/java/cn/nukkit/block/BlockPressurePlateBase.java
https://github.com/Nukkit/Nukkit/issues/2020
> Fix pressure plate spam bug

- src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java
Hoppers would not push if there was a hopper below and hoppers transferred to furnaces incorrectly. Fixed both of these issues.
> Hopper Fixes

- src/main/java/cn/nukkit/item/ItemBucket.java
- Make fish buckets place water
- Add sounds for buckets
- No water in nether
> Improvements for buckets

- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/level/format/LevelProvider.java
- src/main/java/cn/nukkit/level/format/anvil/Anvil.java
- src/main/java/cn/nukkit/level/format/leveldb/LevelDB.java
- src/main/java/cn/nukkit/level/format/mcregion/McRegion.java
This will also fix //regen in FAWE.
> Fix regenerateChunk method

- src/main/java/cn/nukkit/block/BlockLiquid.java
- src/main/java/cn/nukkit/event/block/LiquidFlowEvent.java
This event allows you to get liquid flow source.
test with SRP`s liquid flow flag which prevents liquid from flowing into region https://youtu.be/tL1tM7IKiGg
> LiquidFlowEvent

- src/main/java/cn/nukkit/block/BlockLiquid.java
Fix liquid breaking nearest blocks
> Fix liquid breaking nearest blocks

- src/main/java/cn/nukkit/item/ItemPotionSplash.java
> Improved motion for Splash Potion

- src/main/java/cn/nukkit/entity/EntityLiving.java
Fix for regeneration hit delay resulting in 0 attack time
> Fix for Regeneration Hit Bug

- src/main/java/cn/nukkit/potion/Effect.java
Added few missing effects. I need the levitation effect for shulkers in Mob Plugin.
> List some effects

- src/main/resources/recipes.json
> Update recipes.json to 1.9

- src/main/java/cn/nukkit/potion/Effect.java
and added missing SlowFalling effect
> Fix ConduitPower RGB color

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/command/defaults/TitleCommand.java
- src/main/java/cn/nukkit/event/server/PlayerDataSerializeEvent.java
- src/main/java/cn/nukkit/utils/DefaultPlayerDataSerializer.java
- src/main/java/cn/nukkit/utils/PlayerDataSerializer.java
This allows for custom player data serializers to be set so the data can be stored in places other default `players/` directory.
> Player Data Serializer

- src/main/java/cn/nukkit/Server.java
Register them to make them save when unloading the world
> Register all minecart types

- src/main/java/cn/nukkit/inventory/PlayerInventory.java
> Fix player inventory send

- src/main/java/cn/nukkit/Player.java
This allows access to the top window current open by the player.
> Add a method to get the top open window.

- src/main/java/cn/nukkit/entity/item/EntityVehicle.java
Remove some extra packets being sent which caused a player to stay linked with the boat.
> Fix Boat Dismounting

- src/main/java/cn/nukkit/block/BlockLava.java
- src/main/java/cn/nukkit/block/BlockLiquid.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/item/EntityFallingBlock.java
- src/main/java/cn/nukkit/entity/item/EntityPrimedTNT.java
> Fixed falling blocks getting moved by currents

- src/main/java/cn/nukkit/item/ProjectileItem.java
> Improved GetThrowForce

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/item/EntityFishingHook.java
- src/main/java/cn/nukkit/inventory/PlayerInventory.java
- Stop fishing if player go too far away from the hook
- Always stop fishing when player die
- Improve hook movement
- Don't allow switching to another rod without stopping fishing
> Improvements to fishing

- src/main/java/cn/nukkit/Player.java
Taking damage does not affect hunger.
Clicking fast on player fixed by lowering the cool down
> Fix Food Change Event Fix #474

- src/main/java/cn/nukkit/Player.java
Try to reduce false positives and kicks
Should fix #353 and #611 + make disabling movement checks more powerful
> Update movement checks

- src/main/java/cn/nukkit/network/Network.java
- src/main/java/cn/nukkit/network/protocol/ScriptCustomEventPacket.java
Will be useful for upcoming client script support. Also useful today as a message channel to an upstream proxy.
> adding ScriptCustomEventPacket

- src/main/java/cn/nukkit/blockentity/BlockEntityFurnace.java
This PR makes those fields protected instead of private, so developers now would be able to create their own furnace class (extended from original) and control the fields. Maybe should I add getters and setters of these fields to make it more easier to change the fields (without having to create own class)?
> Allow devs to manage furnace burning/cooking process.

- src/main/java/cn/nukkit/entity/Entity.java
pos.getLevel().getChunk(pos.getFloorX() **>> 4**, pos.getFloorZ() **>> 4**)
> Fix incorrect chunk coord

- .travis.yml
Hopefully this should fix the build errors.
> Use openjdk8 for Travis.

- src/main/java/cn/nukkit/item/food/Food.java
Fixes #728 (bowl not adding after eating beetroot soup).
> Fixes #728 (bowl not adding after eating beetroot soup)

- src/main/java/cn/nukkit/level/biome/Biome.java
Plugins should not use deprecated  APIs
https://github.com/NukkitX/Nukkit/blob/70221f68807c63a62d18497f67589a77cfce4716/src/main/java/cn/nukkit/level/biome/EnumBiome.java#L120-L122
https://github.com/NukkitX/Nukkit/blob/70221f68807c63a62d18497f67589a77cfce4716/src/main/java/cn/nukkit/level/biome/EnumBiome.java#L131-L133
> Make the getBiome method public

- src/main/java/cn/nukkit/entity/Entity.java
I was very surprised to learn that this flag is not stored in Entity NBT
> Implement NametagAlwaysVisible flag saving\loading

- src/main/java/cn/nukkit/network/Network.java
- src/main/java/cn/nukkit/network/protocol/ScriptCustomEventPacket.java
Forgot to add the reset() in encode, also did some other cleanup.
> Fix ScriptCustomEventPacket

- src/main/java/cn/nukkit/level/particle/Particle.java
> Update particle IDs for 1.12

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/projectile/EntityArrow.java
- src/main/java/cn/nukkit/item/ItemBow.java
Fired arrows cannot be retrieved except in Creative mode (where they are erased instead of added to the player's inventory).
> Arrows cannot be retrieved if shot by a infinity enchanted bow

- src/main/java/cn/nukkit/Player.java
Disable dimensions on join until dimension changes are fixed
> Temporary fix #748

- src/main/java/cn/nukkit/block/BlockLeaves.java
- src/main/java/cn/nukkit/block/BlockLeaves2.java
Fixes https://github.com/NukkitX/Nukkit/issues/852
> Fix leaves

- src/main/java/cn/nukkit/level/biome/impl/extremehills/ExtremeHillsMBiome.java
- src/main/java/cn/nukkit/level/biome/impl/mesa/MesaBiome.java
- src/main/java/cn/nukkit/level/biome/type/CoveredBiome.java
- src/main/java/cn/nukkit/level/generator/Flat.java
- src/main/java/cn/nukkit/level/generator/Nether.java
- src/main/java/cn/nukkit/level/generator/Normal.java
- src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorGroundCover.java
- src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorOre.java
untested, but this is basically just a simple refactor of the existing system to avoid an additional mutex
> remove mutex on ground cover populator

- src/main/java/cn/nukkit/Player.java
> Fix sendPopup method

- src/main/java/cn/nukkit/raknet/server/UDPServerSocket.java
> Clean UDP Socket

- src/main/java/cn/nukkit/level/generator/Normal.java
Avoid this: https://cdn.discordapp.com/attachments/624551363757735936/624576333942620177/unknown.png
> Disable broken ravines from world generation

- src/main/java/cn/nukkit/block/BlockBed.java
Fix falling blocks duplication if there is two fallable blocks top of a bed
Fix #884
> Fix falling block dupe

- src/main/java/cn/nukkit/block/BlockSapling.java
> Fix acacia tree growing

- src/main/java/cn/nukkit/entity/item/EntityBoat.java
- src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java
https://github.com/SkyBlockPE/Skyblock-Bugs/issues/34
> Fix boats make item in hand disappear

- src/main/java/cn/nukkit/Player.java
Players should be able to hit eachother in peaceful
> Incorrect gameplay

- src/main/java/cn/nukkit/block/BlockBed.java
> Fix bed dupe

- src/main/java/cn/nukkit/block/BlockCocoa.java
- src/main/java/cn/nukkit/block/BlockCrops.java
- src/main/java/cn/nukkit/block/BlockDandelion.java
- src/main/java/cn/nukkit/block/BlockDoublePlant.java
- src/main/java/cn/nukkit/block/BlockFlower.java
- src/main/java/cn/nukkit/block/BlockGrass.java
- src/main/java/cn/nukkit/block/BlockGrassPath.java
- src/main/java/cn/nukkit/block/BlockMushroom.java
- src/main/java/cn/nukkit/block/BlockSapling.java
- src/main/java/cn/nukkit/block/BlockSugarcane.java
- src/main/java/cn/nukkit/block/BlockTallGrass.java
- src/main/java/cn/nukkit/level/generator/object/ObjectTallGrass.java
- src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorGrass.java
> Make the bone meal behave like in vanilla

- src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
> Add network id for fox to AddEntityPacket

- src/main/java/cn/nukkit/network/protocol/BossEventPacket.java
- src/main/java/cn/nukkit/utils/DummyBossBar.java
This should fix https://github.com/NukkitX/Nukkit/issues/813
> Fix BossBar length

- src/main/java/cn/nukkit/entity/data/Skin.java
> Fix "Invalid legacy cape" on Human entities

- src/main/java/cn/nukkit/level/GameRule.java
- src/main/java/cn/nukkit/level/GameRules.java
- src/main/java/cn/nukkit/level/Level.java
> Implement random tick speed gamerule

- src/main/java/cn/nukkit/Player.java
PMMP: https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/Player.php#L2406
> Hack fix for packet spam on RIGHT_CLICK_BLOCK

- src/main/java/cn/nukkit/block/BlockSignPost.java
* Fix default toggle element value
* Fix sign facing
> sign-fix (#976)

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/item/EntityExpBottle.java
- src/main/java/cn/nukkit/entity/item/EntityXPOrb.java
- src/main/java/cn/nukkit/level/Level.java
The experience value of the experience orb will now be saved. In addition, the size of the orb will be determined by the amount of experience.
> Fix experience orb

- src/main/java/cn/nukkit/network/protocol/BlockPickRequestPacket.java
> Fix BlockPickRequestPacket encoding #979

- src/main/java/cn/nukkit/block/BlockLeaves.java
- src/main/java/cn/nukkit/block/BlockLeaves2.java
- src/main/java/cn/nukkit/block/BlockSapling.java
Sapling damage was incorrect and leaves returned wrong damage values.
> Fix saplings and leaves

- src/main/java/cn/nukkit/block/BlockItemFrame.java
Fix https://github.com/NukkitX/Nukkit/issues/606
> The ItemFrame is too hard

- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/level/generator/task/PopulationTask.java
`ChunkPopulateEvent` will now be called normally.
> Fix ChunkPopulateEvent

- src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
> Add network id for bee to AddEntityPacket

- src/main/java/cn/nukkit/Player.java
Adds survival block pick and creative item pick does not duplicate block if its in inventory
Tested: yes
> Vanilla Block Pick

- src/main/java/cn/nukkit/item/ItemBucket.java
- src/main/java/cn/nukkit/level/Level.java
> Fix water again

- src/main/java/cn/nukkit/event/block/BlockBreakEvent.java
- src/main/java/cn/nukkit/level/Level.java
Will allow plugins to modify using an event handler and doing event.setDropExp(int);
> Add block drop experience to BlockBreakEvent 

- src/main/java/cn/nukkit/entity/Entity.java
also, if using access methods  for height/width, should use it for scale as well instead of directly accessing properties
> add scale to the width attribute in setPosition()

- src/main/java/cn/nukkit/entity/Entity.java
> fix recalculateBoundingBox()

- src/main/java/cn/nukkit/block/BlockUndyedShulkerBox.java
> Fix ShulkerBox issues

- src/main/java/cn/nukkit/entity/item/EntityItem.java
To reproduce, just drop some items in the air, they weren't moving smoothly.
Video:
[![](http://img.youtube.com/vi/dNmMWqEfsWk/0.jpg)](http://www.youtube.com/watch?v=dNmMWqEfsWk "")
> Fixes dropped items teleporting on every movement

- src/main/java/cn/nukkit/Player.java
> Don't broadcast spam

- src/main/java/cn/nukkit/block/BlockBanner.java
- src/main/java/cn/nukkit/block/BlockBeacon.java
- src/main/java/cn/nukkit/block/BlockBrewingStand.java
> Use BlockEntity.createBlockEntity to create block entities

- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/level/chunk/Chunk.java
- src/main/java/cn/nukkit/level/chunk/ChunkBuilder.java
- src/main/java/cn/nukkit/level/chunk/IChunk.java
- src/main/java/cn/nukkit/level/chunk/LockableChunk.java
- src/main/java/cn/nukkit/level/chunk/UnsafeChunk.java
- src/main/java/cn/nukkit/level/generator/function/ChunkPopulateFunction.java
- src/main/java/cn/nukkit/level/manager/LevelChunkManager.java
- src/main/java/cn/nukkit/registry/RegistryProvider.java
Reverts NukkitX/Nukkit#1094
it was too broken
> Revert "Prevent access to chunks that haven't had themselves or their neighbors populated"

- src/main/java/cn/nukkit/Player.java
fixes #380, #396, #508, #679, #680.
> Send all attributes when the player first spawns

- src/main/java/cn/nukkit/network/Network.java
> Fix register PlayerHotbarPacket

- src/main/java/cn/nukkit/entity/Entity.java
Before:![Minecraft 31 1 2020 17 30 41](https://user-images.githubusercontent.com/26197131/73551656-7d173700-444f-11ea-9f2e-4444ac645bfd.png)
After:
> Fix black texture of offhand items

- src/main/java/cn/nukkit/Player.java
> Fix speed effect not working after rejoin

- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityDrowned.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityHusk.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityPhantom.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntitySkeleton.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityStray.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityWither.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityWitherSkeleton.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityZombie.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityZombiePigman.java
- src/main/java/cn/nukkit/entity/impl/hostile/EntityZombieVillager.java
- src/main/java/cn/nukkit/entity/impl/misc/EntityAreaEffectCloud.java
- src/main/java/cn/nukkit/entity/impl/passive/EntitySkeletonHorse.java
- src/main/java/cn/nukkit/entity/impl/passive/EntityZombieHorse.java
- src/main/java/cn/nukkit/potion/Potion.java
> [2.0] adds isUndead() and inverts potion effects when it's true

- src/main/java/cn/nukkit/level/Level.java
Very often, the time is different between the players and the server. It's going either faster or slower. This should change the time correctly
> Time send corrections

- src/main/java/cn/nukkit/block/BlockBlueIce.java
- src/main/java/cn/nukkit/registry/BlockRegistry.java
> [2.0] Implements Blue Ice

- src/main/java/cn/nukkit/inventory/PlayerInventory.java
> Clears the offhand slot by PlayerInventory.clearAll()

- src/main/java/cn/nukkit/block/BlockSmoothStone.java
- src/main/java/cn/nukkit/registry/BlockRegistry.java
> [2.0] Implements the Smooth Stone Block

- src/main/java/cn/nukkit/block/Block.java
- src/main/java/cn/nukkit/block/BlockBlueIce.java
- src/main/java/cn/nukkit/block/BlockIce.java
- src/main/java/cn/nukkit/block/BlockIcePacked.java
- src/main/java/cn/nukkit/level/Level.java
This fixes the conditions which the ice will become water when broken.
Evolution and reference: GameModsBr#155
> [2.0] Fix the ice break conditions

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/block/BlockBarrel.java
- src/main/java/cn/nukkit/blockentity/BlockEntity.java
- src/main/java/cn/nukkit/blockentity/BlockEntityBarrel.java
- src/main/java/cn/nukkit/inventory/BarrelInventory.java
- src/main/java/cn/nukkit/inventory/InventoryType.java
- src/main/java/cn/nukkit/registry/BlockRegistry.java
> [2.0] Implements the Barrel block

- src/main/java/cn/nukkit/block/BlockTrapdoor.java
It was changing the incorrect bit.
Reference: GameModsBr#158
> [2.0] Fixes trapdoor behaviour on redstone signal

- src/main/java/cn/nukkit/block/BlockDriedKelp.java
- src/main/java/cn/nukkit/inventory/Fuel.java
- src/main/java/cn/nukkit/registry/BlockRegistry.java
History and reference: GameModsBr#162
I also reorganized the registrations at `BlockRegistry` to reduce the amount of conflicts and make them easier to resolve or even auto-resolvable.
> [2.0] Implements the Dried Kelp Block

- src/main/java/cn/nukkit/Player.java
> Fix health check in doFirstSpawn

- src/main/java/cn/nukkit/block/BlockChest.java
> adds waterlogging for chests

- src/main/java/cn/nukkit/block/BlockSignPost.java
- src/main/java/cn/nukkit/block/BlockWallSign.java
- src/main/java/cn/nukkit/registry/BlockRegistry.java
- src/main/java/cn/nukkit/registry/ItemRegistry.java
> [2.0] Implements all wooden sign variants

- src/main/java/cn/nukkit/block/BlockLever.java
> [2.0] Fixes lever switch sound pitch

- src/main/java/cn/nukkit/block/BlockBed.java
- src/main/java/cn/nukkit/player/Player.java
Updates the data type to be a Vector3i in the set EntityData, since the EntityDataType.from() method requires it to match Vector3i.class, so passing a BlockPosition will fail. 
Also changes to match vanilla BDS behavior of saving respawn point even during the day.
> [2.0] fixes beds

- src/main/java/cn/nukkit/block/BlockLight.java
- src/main/java/cn/nukkit/registry/BlockRegistry.java
> [2.0] Implements the Light Block

- src/main/java/cn/nukkit/item/ItemHoneyBottle.java
- src/main/java/cn/nukkit/item/ItemHoneycomb.java
- src/main/java/cn/nukkit/item/food/Food.java
- src/main/java/cn/nukkit/item/food/FoodHoney.java
- src/main/java/cn/nukkit/registry/ItemRegistry.java
> [2.0] Implements Honey Bottle and registers the Honeycomb item

- src/main/java/cn/nukkit/entity/impl/Human.java
- src/main/java/cn/nukkit/inventory/InventoryType.java
- src/main/java/cn/nukkit/inventory/PlayerInventory.java
- src/main/java/cn/nukkit/inventory/PlayerUIInventory.java
- src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/network/protocol/types/InventoryTransactionUtils.java
- src/main/java/cn/nukkit/player/Player.java
~~Fixes the fact that `sendContents()` was being called before the Player was set as spawned, so the InventoryContents were not sent.~~
Reverted sendContents() location. 
Changed sendContents() to allow to send to non-spawned players
Added OffHand to PlayerInventory
> [2.0/protocol-lib] Inventory Changes

- src/main/java/cn/nukkit/item/Item.java
Still is something not right with client<->server item data exchange, but i didn't figure out it yet.
> [2.0] Add saving lore to saveAdditionalData.

- src/main/java/cn/nukkit/level/Level.java
I'm not sure if it also should setData(0).
> [2.0] Fix sendWeather.

- src/main/java/cn/nukkit/entity/impl/Human.java
- src/main/java/cn/nukkit/item/Item.java
- src/main/java/cn/nukkit/level/particle/FloatingTextParticle.java
- src/main/java/cn/nukkit/player/Player.java
This PR changes login sequence to 2.0 order.
> [2.0] Potentially fix login crashes.

- src/main/java/cn/nukkit/block/BlockFence.java
suspicious damage value :thinking:
> Update damage value in BlockFence.java

- src/main/java/cn/nukkit/block/BlockSignPost.java
- src/main/java/cn/nukkit/blockentity/Sign.java
- src/main/java/cn/nukkit/blockentity/impl/SignBlockEntity.java
```
[SERVER BOUND]  -  BlockEntityDataPacket(blockPosition=(294, 65, 453), data=TAG_Compound: 7 entries
(
TAG_Int("x"): 294
TAG_Int("y"): 65
TAG_String("Text"): dsdsdsd
TAG_Byte("isMovable"): 1
TAG_Int("z"): 453
TAG_String("id"): Sign
TAG_String("TextOwner"): 2535409310988082
))
```
Mojang changed tag name?
> [2.0] Actually now fix signs.

- src/main/java/cn/nukkit/Player.java
Use correct max fishing distance (33 blocks) + don't run the distance check on every tick
> Correct max fishing distance

- src/main/java/cn/nukkit/level/Level.java
Fix BlockBreakEvent not being cancelled in some cases even the block breaking is
Someone who knows how this is supposed to work please check is this correct
> A fix for block break event

- src/main/java/cn/nukkit/entity/impl/BaseEntity.java
- src/main/java/cn/nukkit/entity/impl/Human.java
- src/main/java/cn/nukkit/player/Player.java
- src/main/java/cn/nukkit/player/handler/PlayerPacketHandler.java
Took packet handling to own class.
> [2.0] Refactor player onDataPacket

- src/main/java/cn/nukkit/item/ItemBanner.java
> Fix crafting banners crashes the game

- src/main/java/cn/nukkit/block/BlockLiquid.java
- src/main/java/cn/nukkit/event/block/BlockFromToEvent.java
> [2.0] Update BlockFromToEvent 

- src/main/java/cn/nukkit/block/BlockUndyedShulkerBox.java
> Revert "Fix shulker box dont contain copied items"

- src/main/java/cn/nukkit/network/protocol/AvailableCommandsPacket.java
- src/main/java/cn/nukkit/network/protocol/CraftingEventPacket.java
- src/main/java/cn/nukkit/network/protocol/InventoryContentPacket.java
- src/main/java/cn/nukkit/network/protocol/InventoryTransactionPacket.java
- src/main/java/cn/nukkit/network/protocol/TextPacket.java
- src/main/java/cn/nukkit/utils/BinaryStream.java
We should limit the length of arrays when decoding.
> Fix Array Allocation Vulnerability

- src/main/java/cn/nukkit/level/GlobalBlockPalette.java
- src/main/java/cn/nukkit/level/format/ChunkSection.java
- src/main/java/cn/nukkit/level/format/anvil/Anvil.java
- src/main/java/cn/nukkit/level/format/anvil/ChunkSection.java
- src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java
- src/main/java/cn/nukkit/level/format/generic/EmptyChunkSection.java
- src/main/java/cn/nukkit/level/format/leveldb/LevelDB.java
- src/main/java/cn/nukkit/level/format/mcregion/McRegion.java
- src/main/java/cn/nukkit/level/util/BitArray.java
- src/main/java/cn/nukkit/level/util/BitArrayVersion.java
- src/main/java/cn/nukkit/level/util/PaddedBitArray.java
- src/main/java/cn/nukkit/level/util/PalettedBlockStorage.java
- src/main/java/cn/nukkit/level/util/Pow2BitArray.java
This fixes some of the major lag that has been occurring since 1.13. Legacy chunk conversion on the client has been so slow that some people can't even join.
> Convert to latest chunk format on send.

- src/main/java/cn/nukkit/utils/ThreadCache.java
- src/main/java/cn/nukkit/utils/Zlib.java
- src/main/java/cn/nukkit/utils/ZlibOriginal.java
- src/main/java/cn/nukkit/utils/ZlibProvider.java
- src/main/java/cn/nukkit/utils/ZlibSingleThreadLowMem.java
- src/main/java/cn/nukkit/utils/ZlibThreadLocal.java
Before it was checking the input buffer size 🤦‍♂️
Fixes #1322
> Check the maximum size of Zlib decompressed data

- src/main/java/cn/nukkit/block/BlockItemFrame.java
Allows placement on solid transparent blocks such as chests.
> [1.0] Fix frame placement

- src/main/java/cn/nukkit/entity/EntityHuman.java
- src/main/java/cn/nukkit/entity/data/Skin.java
- src/main/java/cn/nukkit/network/protocol/LoginPacket.java
- src/main/java/cn/nukkit/network/protocol/PlayerListPacket.java
- src/main/java/cn/nukkit/network/protocol/PlayerSkinPacket.java
- src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
- src/main/java/cn/nukkit/utils/BinaryStream.java
- src/main/java/cn/nukkit/utils/PersonaPiece.java
- src/main/java/cn/nukkit/utils/PersonaPieceTint.java
Download:
https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/feature%252F1.14.60/
Closes #1344
> Bedrock 1.14.60

- src/main/java/cn/nukkit/block/BlockPumpkinLit.java
> Fix BlockPumpkinLit

- src/main/java/cn/nukkit/blockentity/BlockEntityBrewingStand.java
- src/main/java/cn/nukkit/blockentity/BlockEntityFurnace.java
- src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java
- src/main/java/cn/nukkit/entity/item/EntityMinecartChest.java
- src/main/java/cn/nukkit/entity/item/EntityMinecartHopper.java
This should fix at least one of the minecart dupes
> Clear inventory after its contents are dropped

- src/main/java/cn/nukkit/block/BlockEndPortal.java
Fix https://github.com/Nukkit/Nukkit/issues/2056
> Make water not to break end portal

- src/main/java/cn/nukkit/block/BlockSugarcane.java
Added call BlockGrowEvent in Sugarcane
> Added call BlockGrowEvent

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/event/player/PlayerJumpEvent.java
> Added PlayerJumpEvent

- src/main/java/cn/nukkit/block/BlockPrismarine.java
Fix to
0: Prismarine
1: Dark Prismarine
2: Prismarine Bricks
> Fix Primarine Dark and Brick Data Value

- src/main/java/cn/nukkit/command/defaults/SpawnpointCommand.java
Coordinates should be int and not double
> [2.0] Fix spawnpoint

- src/main/java/cn/nukkit/nbt/tag/ShortTag.java
> Fix ShortTag loading

- src/main/java/cn/nukkit/command/defaults/EnchantCommand.java
- src/main/java/cn/nukkit/command/defaults/GamemodeCommand.java
- src/main/java/cn/nukkit/entity/impl/EntityLiving.java
- src/main/java/cn/nukkit/event/entity/EntityDamageByEntityEvent.java
- src/main/java/cn/nukkit/player/GameMode.java
- src/main/java/cn/nukkit/player/Player.java
- src/main/java/cn/nukkit/player/handler/PlayerPacketHandler.java
- remove movement checks (fixes movement glitches)
- fix bugs with gamemode
- fix enchant command translation
- use vanilla knockback
- fix player gamemode saving
- fix player Y offset after teleport
- fix gamemode command permission check
> Fix various bugs

- src/main/java/cn/nukkit/network/Network.java
Fix #1539 
More info:
* https://github.com/PowerNukkit/PowerNukkit/issues/390
* https://stackoverflow.com/questions/55366393/java-inflater-will-loop-infinitely-sometimes
> Fix: Server stop responding due to a compression issue

- src/main/java/cn/nukkit/Player.java
Sync callback should be now always called after the initial login process
> Async login fix

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/entity/passive/EntityBee.java
- src/main/java/cn/nukkit/item/Item.java
- src/main/java/cn/nukkit/item/ItemHoneyBottle.java
- src/main/java/cn/nukkit/item/ItemHoneycomb.java
- src/main/java/cn/nukkit/item/ItemID.java
- src/main/java/cn/nukkit/item/food/Food.java
Add Bee Entity
Add Honey Bottle Item
Add Honeycomb Item
> Add Bee Entity and two more items

- src/main/java/cn/nukkit/block/BlockTorch.java
> Fix torch placement on glass

- src/main/java/cn/nukkit/item/ItemBucket.java
- No buckets in adventure mode (Fix #794)
- No milk buckets in spectator mode
- Implement fish buckets
- Drop buckets when inventory is full
> Bucket fixes and improvements

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/level/Level.java
> Make getSafeSpawn() account for non-generated chunks

- src/main/java/cn/nukkit/Player.java
Idea from pr 1584, idk why they didn't want that to get this merged
> Totem doesn't save from suicide

- src/main/java/cn/nukkit/Server.java
> parse difficulty from string

- src/main/java/cn/nukkit/utils/DefaultPlayerDataSerializer.java
Make this class more flexible, so youre able to use it for e.g. on other directories and hold no server instance.
> Better constructor for DefaultPlayerDataSerializer

- src/main/java/cn/nukkit/Server.java
this will prevent a null value for the data path
> change initialization of DefaultPlayerDataSerializer

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/EntityHuman.java
- src/main/java/cn/nukkit/inventory/ContainerInventory.java
- src/main/java/cn/nukkit/inventory/FakeBlockUIComponent.java
- src/main/java/cn/nukkit/inventory/PlayerEnderChestInventory.java
- src/main/java/cn/nukkit/inventory/PlayerInventory.java
- src/main/java/cn/nukkit/network/protocol/LoginPacket.java
- src/main/java/cn/nukkit/utils/BinaryStream.java
- src/main/java/cn/nukkit/utils/SkinAnimation.java
- Fixed client crashing on Windows 10 (when you use persona-skin).
- Added new parameter for SkinAnimation - "AnimationExpression".
- Fixed commands enabling.
- Fixed opening / closing inventories on client-side.
> Fixes for skins, commands and inventories

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/entity/EntityHuman.java
This commit fixes the bug that the skin and geometry of the entity humans will be loaded.
> fix for skin + geometry, for entityhumans

- src/main/java/cn/nukkit/entity/Entity.java
> implement that Haybales reduce fall damage

- src/main/java/cn/nukkit/potion/Effect.java
`COUNDIT_POWER` → `CONDUIT_POWER`
> Fix a typo

- src/main/java/cn/nukkit/entity/item/EntityBoat.java
- src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java
- src/main/java/cn/nukkit/item/RuntimeItems.java
> No smoke particles on boat/minecart death

- src/main/java/cn/nukkit/AdventureSettings.java
- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/item/EntityBoat.java
- src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java
- src/main/java/cn/nukkit/entity/item/EntityPainting.java
- src/main/java/cn/nukkit/item/ItemBoat.java
- src/main/java/cn/nukkit/item/ItemBow.java
- src/main/java/cn/nukkit/item/ItemEdible.java
- src/main/java/cn/nukkit/item/ItemEndCrystal.java
- src/main/java/cn/nukkit/item/ItemFireCharge.java
- src/main/java/cn/nukkit/item/ItemFirework.java
- src/main/java/cn/nukkit/item/ItemFlintSteel.java
- src/main/java/cn/nukkit/item/ItemMinecart.java
- src/main/java/cn/nukkit/item/ItemMinecartChest.java
- src/main/java/cn/nukkit/item/ItemMinecartHopper.java
- src/main/java/cn/nukkit/item/ItemMinecartTNT.java
- src/main/java/cn/nukkit/item/ItemPainting.java
- src/main/java/cn/nukkit/item/ItemPotion.java
- src/main/java/cn/nukkit/item/ItemSpawnEgg.java
* Fix breaking blocks client side in spectator gamemode
* Fix projectiles, boats, end crystals, foods, flint & steel, fire charge, firework, minecarts & potions not decrementing in adventure gamemode
* Fix painting not dropping when damaged by player in adventure gamemode
* Fix placing painting in adventure gamemode
* Fix using fireworks & spawn eggs in adventure gamemode
* Some improvements in code
> Fixes & improvements

- src/main/java/cn/nukkit/entity/EntityHuman.java
updatePlayerListData is already used with player display name elsewhere so make sure it's not overwritten in spawnTo
> Use player display name in updatePlayerListData

- src/main/java/cn/nukkit/metrics/NukkitMetrics.java
I see PowerNukkit has already merged in metrics...so here we go
> Add server codename to metrics

- src/main/java/cn/nukkit/item/ItemArmor.java
This pull request allows players to equip armor pieces regardless of if the armor slot was full.
If it was full, it will trade places with the armor we are equipping. (Fixes #1782)
> Allow equipping equipping armor with something on already

- pom.xml
> Bump GSON version

- src/main/java/cn/nukkit/block/BlockRail.java
- src/main/java/cn/nukkit/block/BlockRedstoneWire.java
> Fix cannot place rails & redstone wire on hopper

- src/main/java/cn/nukkit/item/ItemBucket.java
Set new bucket to the same slot if it's empty + make water buckets to be emptied when used in the nether
> Some improvements for buckets

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/EntityCreature.java
- src/main/java/cn/nukkit/entity/mob/EntityEnderDragon.java
- src/main/java/cn/nukkit/entity/mob/EntityMob.java
- src/main/java/cn/nukkit/entity/passive/EntityAnimal.java
- src/main/java/cn/nukkit/event/server/ServerStopEvent.java
- src/main/java/cn/nukkit/item/ItemPotion.java
> Fix totems not working sometimes

- src/main/java/cn/nukkit/level/particle/Particle.java
> Update particle IDs

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/block/BlockItemFrame.java
- src/main/java/cn/nukkit/blockentity/BlockEntityItemFrame.java
removing items from item frames was broken due to behavioural changes in 1.16.210
> Fix Item Frame interaction

- src/main/java/cn/nukkit/Player.java
> Fix sprinting speed

- src/main/resources/recipes.json
> Fix crafting with charcoal

- src/main/java/cn/nukkit/item/Item.java
- src/main/java/cn/nukkit/item/ItemArmorStand.java
- src/main/java/cn/nukkit/item/ItemBannerPattern.java
- src/main/java/cn/nukkit/item/ItemCarrotOnAStick.java
- src/main/java/cn/nukkit/item/ItemChorusFruitPopped.java
- src/main/java/cn/nukkit/item/ItemDragonBreath.java
- src/main/java/cn/nukkit/item/ItemEmptyMap.java
- src/main/java/cn/nukkit/item/ItemFireworkStar.java
- src/main/java/cn/nukkit/item/ItemFishingRod.java
- src/main/java/cn/nukkit/item/ItemHeartOfTheSea.java
- src/main/java/cn/nukkit/item/ItemID.java
- src/main/java/cn/nukkit/item/ItemLead.java
- src/main/java/cn/nukkit/item/ItemNautilusShell.java
- src/main/java/cn/nukkit/item/ItemNuggetIron.java
- src/main/java/cn/nukkit/item/ItemPhantomMembrane.java
- src/main/java/cn/nukkit/item/ItemRabbitHide.java
- src/main/java/cn/nukkit/item/ItemScute.java
- src/main/java/cn/nukkit/item/ItemShulkerShell.java
- src/main/java/cn/nukkit/item/ItemSuspiciousStew.java
- src/main/java/cn/nukkit/item/ItemTool.java
- src/main/java/cn/nukkit/item/ItemWarpedFungusOnAStick.java
- src/main/java/cn/nukkit/item/food/Food.java
- src/main/java/cn/nukkit/item/randomitem/Fishing.java
This pr fixes certain items not showing up in creative inventory with Nukkit 1.17 [creative items hack](https://github.com/CloudburstMC/Nukkit/blob/6479e036b688eb723a28c77d1db4a46916be5929/src/main/java/cn/nukkit/item/Item.java#L361) because they don't have their own item classes registered
> Fix missing items in creative inventory

- src/main/java/cn/nukkit/item/Item.java
- src/main/java/cn/nukkit/item/ItemID.java
- src/main/java/cn/nukkit/item/ItemSpyglass.java
- src/main/resources/legacy_item_ids.json
- src/main/resources/runtime_item_states.json
https://minecraft.fandom.com/wiki/Spyglass
The item id found on the wiki is 772(Google Translate)
> Add ItemSpyglass

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/item/EntityFishingHook.java
Enchantment Lure can actually make fishing more quickly.
>  Make Enchantment Lure actually do something

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/projectile/EntityProjectile.java
- src/main/java/cn/nukkit/event/entity/EntityDamageByEntityEvent.java
- src/main/java/cn/nukkit/item/enchantment/Enchantment.java
- src/main/java/cn/nukkit/item/enchantment/EnchantmentFireAspect.java
- src/main/java/cn/nukkit/item/enchantment/damage/EnchantmentDamageAll.java
This pr fixes fire aspect not having effect when a mob is killed by the first hit and knockback enchantment not having effect at all
Fix #1453
Fix https://github.com/Nukkit-coders/MobPlugin/issues/149
> Fix fire aspect and knockback

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/network/protocol/ResourcePacksInfoPacket.java
After:
https://user-images.githubusercontent.com/17339354/143472404-ab805d0d-7c16-46ba-ad83-bf11c63be156.mp4
Before:
https://user-images.githubusercontent.com/17339354/143472489-e06e4fc7-3988-433d-b5a9-585e3e71507a.mp4
> Fix resource pack downloading

- src/main/resources/runtime_item_states.json
> Update runtime item states to 1.18

- src/main/java/cn/nukkit/Player.java
Fixes Player#getDummyBossBar javadoc
> Fix Bossbar javadoc

- src/main/java/cn/nukkit/entity/Entity.java
Fix some client side issues caused by normal data flags not being sent with extended flags. Please merge #1935 first.
> Send normal data flags with extended flags

- src/main/java/cn/nukkit/utils/BinaryStream.java
Should be 1 if the item is not air
> Item Net ID

- src/main/java/cn/nukkit/Player.java
Currently many movement packets are dropped in certain situations and it could make viewers unable to see all movement https://streamable.com/ratxk1
> Make player movement more accurate

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/entity/EntityHuman.java
- src/main/java/cn/nukkit/entity/data/Skin.java
- src/main/java/cn/nukkit/network/protocol/LoginPacket.java
> Fixes for skin data & in game changing

- src/main/java/cn/nukkit/command/defaults/KillCommand.java
> Fix CCE caused by Kill command

- src/main/java/cn/nukkit/block/BlockRailActivator.java
https://user-images.githubusercontent.com/17339354/158084014-a654ee52-4e58-4470-ab88-499055591417.mp4
> Fix Activator Rail duplication

- src/main/java/cn/nukkit/entity/Entity.java
- src/main/java/cn/nukkit/entity/item/EntityItem.java
> Correct entity spawn position

- src/main/java/cn/nukkit/block/BlockRedstoneWire.java
https://user-images.githubusercontent.com/17339354/172020432-676c8dcb-b282-440d-ac72-e9880c67595a.mp4
> Fix duplicate redstone update

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/network/Network.java
- src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
- src/main/java/cn/nukkit/network/protocol/ToastRequestPacket.java
> Implement toast notifications

- src/main/java/cn/nukkit/entity/item/EntityFirework.java
> Fix firework entity data

- src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
- src/main/java/cn/nukkit/network/protocol/AddPlayerPacket.java
- src/main/java/cn/nukkit/network/protocol/EntityEventPacket.java
- src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java
- src/main/java/cn/nukkit/network/protocol/PlayStatusPacket.java
- src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
- src/main/java/cn/nukkit/network/protocol/StartGamePacket.java
> Support for 1.19.10

- src/main/java/cn/nukkit/Player.java
> Fix type when getting chunk pos

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/event/player/PlayerToggleGlideEvent.java
These have been broken since implementation of server authenticated movement
Fix https://github.com/CloudburstMC/Nukkit/issues/2044
Fix https://github.com/CloudburstMC/Nukkit/issues/2033
> Fix swimming, sprinting, sneaking & gliding

- src/main/java/cn/nukkit/Player.java
Fix https://github.com/CloudburstMC/Nukkit/issues/2042
> Fix player block collisions

- src/main/java/cn/nukkit/item/ItemElytra.java
- src/main/java/cn/nukkit/item/enchantment/EnchantmentType.java
Elytras can't have protection etc enchantments
> Elytra isArmor & canEnchantItem

- src/main/java/cn/nukkit/Player.java
Below:
```
if (distance != 0 && this.nextChunkOrderRun > 20) {
this.nextChunkOrderRun = 20;
}
```
> Make sure updateFoodExpLevel calculations won't affect nextChunkOrderRun

- src/main/java/cn/nukkit/Player.java
Fix https://github.com/CloudburstMC/Nukkit/issues/1499
> teleportImmediate: don't close permanent inventories + update boss bar

- src/main/resources/creative_items.json
Fix https://github.com/CloudburstMC/Nukkit/issues/2119
> Fix creative items

- build.gradle.kts
- gradle/libs.versions.toml
- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/level/Level.java
- src/main/java/cn/nukkit/network/Network.java
- src/main/java/cn/nukkit/network/encryption/EncryptionUtils.java
- src/main/java/cn/nukkit/network/encryption/PrepareEncryptionTask.java
- src/main/java/cn/nukkit/network/protocol/DataPacket.java
- src/main/java/cn/nukkit/network/protocol/ServerToClientHandshakePacket.java
- src/main/java/cn/nukkit/network/session/NetworkPlayerSession.java
- src/main/java/cn/nukkit/network/session/RakNetPlayerSession.java
- src/main/java/cn/nukkit/utils/ClientChainData.java
Implemented network encryption & batching threshold + made some code cleanup
Note: nukkit.yml doesn't update automatically. Add network.encryption: true to enable encryption (if you are not using a proxy). Default setting for batching threshold exists already.
> Encryption & batching threshold

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- README.md
- src/main/java/cn/nukkit/command/SimpleCommandMap.java
Unregistered debugpaste command as Hastebin no longer allows unauthenticated uploads. Also removed mentions of it from issue template and updated some links.
> Unregister /debugpaste

- src/main/java/cn/nukkit/Server.java
- src/main/java/cn/nukkit/resourcepacks/AbstractResourcePack.java
- src/main/java/cn/nukkit/resourcepacks/JarPluginResourcePack.java
- src/main/java/cn/nukkit/resourcepacks/ResourcePack.java
- src/main/java/cn/nukkit/resourcepacks/ResourcePackManager.java
- src/main/java/cn/nukkit/resourcepacks/ZippedResourcePack.java
- src/main/java/cn/nukkit/resourcepacks/loader/JarPluginResourcePackLoader.java
- src/main/java/cn/nukkit/resourcepacks/loader/ResourcePackLoader.java
- src/main/java/cn/nukkit/resourcepacks/loader/ZippedResourcePackLoader.java
This lets the server to load resource packs inside plugin Jar files
resource pack dir in the jar file under the resources folder : `resources/assets/resource_pack`
> Jar ResourcePack Loading

- src/main/java/cn/nukkit/Player.java
- src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
- src/main/java/cn/nukkit/network/protocol/SetHudPacket.java
- src/main/java/cn/nukkit/network/protocol/types/HudElement.java
- src/main/java/cn/nukkit/scoreboard/Scoreboard.java
Implemented SetHudPacket and `player.setHudElementVisibility(boolean visible, HudElement... elements)`
> Add method to hide hud elements

- src/main/java/cn/nukkit/block/BlockSlab.java
Not sure when their hardness was changed or what's the actual new value but 2 seems to be close enough to what the client expects
Fix #2209
> Fix indestructible slabs

- src/main/java/cn/nukkit/block/BlockSandstone.java
> Fix sandstone hardness & resistance

- src/main/java/cn/nukkit/network/encryption/EncryptionUtils.java
Bringing across from https://github.com/CloudburstMC/Protocol/pull/274
> Fix TLS named groups concatenation
